import AsyncStorage from '@react-native-async-storage/async-storage';
import React, { createContext, ReactNode, useContext, useEffect, useMemo, useState } from 'react';

export type AppLanguage =
  | 'en' // English
  | 'de' // Deutsch
  | 'fr' // Français
  | 'it' // Italiano
  | 'es' // Español
  | 'pl' // Polski
  | 'pt' // Português
  | 'tr' // Türkçe
  | 'ru' // Русский
  | 'id' // Bahasa Indonesia
  | 'ms' // Bahasa Melayu
  | 'th' // ไทย
  | 'vi' // Tiếng Việt
  | 'ja' // 日本語
  | 'ko' // 한국어
  | 'zh' // 中文（简体）
  | 'zh-Hant' // 中文（繁體）
  | 'he' // עברית
  | 'ar'; // العربية
export type AppCurrency = 'USD' | 'EUR' | 'KRW' | 'JPY' | 'CNY';

type SettingsContextType = {
  language: AppLanguage;
  setLanguage: (lang: AppLanguage) => void;
  currency: AppCurrency;
  setCurrency: (cur: AppCurrency) => void;
  locale: string;
  t: (key: string) => string;
  formatCurrency: (value: number, override?: { currency?: AppCurrency; language?: AppLanguage }) => string;
};

const SettingsContext = createContext<SettingsContextType | undefined>(undefined);

const LANGUAGE_KEY = 'app_language';
const CURRENCY_KEY = 'app_currency';

const SUPPORTED_LANGUAGES: AppLanguage[] = [
  'en', 'de', 'fr', 'it', 'es', 'pl', 'pt', 'tr', 'ru', 'id', 'ms', 'th', 'vi', 'ja', 'ko', 'zh', 'zh-Hant', 'he', 'ar',
];

const localeMap: Record<AppLanguage, string> = {
  en: 'en-US',
  de: 'de-DE',
  fr: 'fr-FR',
  it: 'it-IT',
  es: 'es-ES',
  pl: 'pl-PL',
  pt: 'pt-PT',
  tr: 'tr-TR',
  ru: 'ru-RU',
  id: 'id-ID',
  ms: 'ms-MY',
  th: 'th-TH',
  vi: 'vi-VN',
  ja: 'ja-JP',
  ko: 'ko-KR',
  zh: 'zh-CN',
  'zh-Hant': 'zh-TW',
  he: 'he-IL',
  ar: 'ar-SA',
};

const currencySymbols: Record<AppCurrency, string> = {
  USD: '$',
  EUR: '€',
  KRW: '₩',
  JPY: '¥',
  CNY: '¥',
};

// Minimal sample dictionary to demonstrate wiring.
const rawDictionary: Record<string, Partial<Record<AppLanguage, string>>> = {
  Appearance: {
    en: 'Appearance',
    de: 'Darstellung',
    fr: 'Apparence',
    it: 'Aspetto',
    es: 'Apariencia',
    pl: 'Wygląd',
    pt: 'Aparência',
    tr: 'Görünüm',
    ru: 'Внешний вид',
    id: 'Tampilan',
    ms: 'Penampilan',
    th: 'ลักษณะ',
    vi: 'Giao diện',
    ja: '外観',
    ko: '화면',
    zh: '外观',
    'zh-Hant': '外觀',
    he: 'מראה',
    ar: 'المظهر',
  },
  Language: {
    en: 'Language',
    de: 'Sprache',
    fr: 'Langue',
    it: 'Lingua',
    es: 'Idioma',
    pl: 'Język',
    pt: 'Idioma',
    tr: 'Dil',
    ru: 'Язык',
    id: 'Bahasa',
    ms: 'Bahasa',
    th: 'ภาษา',
    vi: 'Ngôn ngữ',
    ja: '言語',
    ko: '언어',
    zh: '语言',
    'zh-Hant': '語言',
    he: 'שפה',
    ar: 'اللغة',
  },
  Currency: {
    en: 'Currency',
    de: 'Währung',
    fr: 'Devise',
    it: 'Valuta',
    es: 'Moneda',
    pl: 'Waluta',
    pt: 'Moeda',
    tr: 'Para birimi',
    ru: 'Валюта',
    id: 'Mata uang',
    ms: 'Mata wang',
    th: 'สกุลเงิน',
    vi: 'Tiền tệ',
    ja: '通貨',
    ko: '통화',
    zh: '货币',
    'zh-Hant': '貨幣',
    he: 'מטבע',
    ar: 'العملة',
  },
  ThemeLight: {
    en: 'Light',
    de: 'Hell',
    fr: 'Clair',
    it: 'Chiaro',
    es: 'Claro',
    pl: 'Jasny',
    pt: 'Claro',
    tr: 'Açık',
    ru: 'Светлая',
    id: 'Terang',
    ms: 'Cerah',
    th: 'สว่าง',
    vi: 'Sáng',
    ja: 'ライト',
    ko: '라이트',
    zh: '浅色',
    'zh-Hant': '淺色',
    he: 'בהיר',
    ar: 'فاتح',
  },
  ThemeDark: {
    en: 'Dark',
    de: 'Dunkel',
    fr: 'Sombre',
    it: 'Scuro',
    es: 'Oscuro',
    pl: 'Ciemny',
    pt: 'Escuro',
    tr: 'Koyu',
    ru: 'Тёмная',
    id: 'Gelap',
    ms: 'Gelap',
    th: 'เข้ม',
    vi: 'Tối',
    ja: 'ダーク',
    ko: '다크',
    zh: '深色',
    'zh-Hant': '深色',
    he: 'כהה',
    ar: 'داكن',
  },
  ThemeSystem: {
    en: 'System',
    de: 'System',
    fr: 'Système',
    it: 'Sistema',
    es: 'Sistema',
    pl: 'System',
    pt: 'Sistema',
    tr: 'Sistem',
    ru: 'Системная',
    id: 'Sistem',
    ms: 'Sistem',
    th: 'ระบบ',
    vi: 'Hệ thống',
    ja: 'システム',
    ko: '시스템',
    zh: '系统',
    'zh-Hant': '系統',
    he: 'מערכת',
    ar: 'النظام',
  },
  UnlockMoreStocks: {
    en: 'Unlock {count} more coins',
    de: 'Schalte {count} weitere Aktien frei',
    fr: 'Débloquez {count} actions supplémentaires',
    it: 'Sblocca altre {count} azioni',
    es: 'Desbloquea {count} acciones más',
    pl: 'Odblokuj jeszcze {count} akcji',
    pt: 'Desbloqueie mais {count} ações',
    tr: '{count} hisse daha aç',
    ru: 'Откройте ещё {count} акций',
    id: 'Buka {count} saham lagi',
    ms: 'Buka {count} saham lagi',
    th: 'ปลดล็อกหุ้นเพิ่มอีก {count} รายการ',
    vi: 'Mở khóa thêm {count} cổ phiếu',
    ja: '{count}銘柄を追加で解放',
    ko: '{count}개의 종목 추가 잠금 해제',
    zh: '解锁更多 {count} 只股票',
    'zh-Hant': '解鎖更多 {count} 檔股票',
    he: 'פתח עוד {count} מניות',
    ar: 'افتح {count} سهمًا إضافيًا',
  },
  CoinsAccessOne: {
    en: '{count} coin • 24h access',
    de: '{count} Münze • 24h Zugriff',
    fr: '{count} pièce • accès 24h',
    it: '{count} moneta • accesso 24h',
    es: '{count} moneda • acceso 24h',
    pl: '{count} moneta • dostęp 24h',
    pt: '{count} moeda • acesso 24h',
    tr: '{count} coin • 24 saat erişim',
    ru: '{count} монета • доступ 24 часа',
    id: '{count} koin • akses 24 jam',
    ms: '{count} syiling • akses 24 jam',
    th: '{count} เหรียญ • ใช้งานได้ 24 ชม.',
    vi: '{count} xu • quyền truy cập 24h',
    ja: '{count}コイン・24時間アクセス',
    ko: '코인 {count}개 • 24시간 이용',
    zh: '{count} 枚硬币 • 24 小时访问',
    'zh-Hant': '{count} 枚硬幣 • 24 小時存取',
    he: '{count} מטבע • גישה ל-24 שעות',
    ar: '{count} عملة • وصول لمدة 24 ساعة',
  },
  CoinsAccessMany: {
    en: '{count} coins • 24h access',
    de: '{count} Münzen • 24h Zugriff',
    fr: '{count} pièces • accès 24h',
    it: '{count} monete • accesso 24h',
    es: '{count} monedas • acceso 24h',
    pl: '{count} monety • dostęp 24h',
    pt: '{count} moedas • acesso 24h',
    tr: '{count} coin • 24 saat erişim',
    ru: '{count} монет • доступ 24 часа',
    id: '{count} koin • akses 24 jam',
    ms: '{count} syiling • akses 24 jam',
    th: '{count} เหรียญ • ใช้งานได้ 24 ชม.',
    vi: '{count} xu • quyền truy cập 24h',
    ja: '{count}コイン・24時間アクセス',
    ko: '코인 {count}개 • 24시간 이용',
    zh: '{count} 枚硬币 • 24 小时访问',
    'zh-Hant': '{count} 枚硬幣 • 24 小時存取',
    he: '{count} מטבעות • גישה ל-24 שעות',
    ar: '{count} عملات • وصول لمدة 24 ساعة',
  },
  RefreshTitle: {
    en: 'yoink!',
    de: 'yoink!',
    fr: 'yoink!',
    it: 'yoink!',
    es: 'yoink!',
    pl: 'yoink!',
    pt: 'yoink!',
    tr: 'yoink!',
    ru: 'yoink!',
    id: 'yoink!',
    ms: 'yoink!',
    th: 'yoink!',
    vi: 'yoink!',
    ja: 'yoink!',
    ko: 'yoink!',
    zh: 'yoink!',
    'zh-Hant': 'yoink!',
    he: 'yoink!',
    ar: 'yoink!',
  },
  // Tabs
  Home: {
    en: 'Home',
    de: 'Start',
    fr: 'Accueil',
    it: 'Home',
    es: 'Inicio',
    pl: 'Start',
    pt: 'Início',
    tr: 'Ana sayfa',
    ru: 'Главная',
    id: 'Beranda',
    ms: 'Laman Utama',
    th: 'หน้าหลัก',
    vi: 'Trang chủ',
    ja: 'ホーム',
    ko: '홈',
    zh: '首页',
    'zh-Hant': '首頁',
    he: 'בית',
    ar: 'الرئيسية',
  },
  Scouters: {
    en: 'Scouters',
    de: 'Scouter',
    fr: 'Éclaireurs',
    it: 'Scout',
    es: 'Exploradores',
    pl: 'Zwiadowcy',
    pt: 'Exploradores',
    tr: 'Keşifçiler',
    ru: 'Скауты',
    id: 'Pengintai',
    ms: 'Peninjau',
    th: 'สเกาต์',
    vi: 'Trinh sát',
    ja: 'スカウター',
    ko: '스카우터',
    zh: '侦察',
    'zh-Hant': '偵察',
    he: 'צופים',
    ar: 'الكشافة',
  },
  Explore: {
    en: 'Explore',
    de: 'Entdecken',
    fr: 'Explorer',
    it: 'Esplora',
    es: 'Explorar',
    pl: 'Odkrywaj',
    pt: 'Explorar',
    tr: 'Keşfet',
    ru: 'Исследовать',
    id: 'Jelajahi',
    ms: 'Teroka',
    th: 'สำรวจ',
    vi: 'Khám phá',
    ja: '探索',
    ko: '탐색',
    zh: '探索',
    'zh-Hant': '探索',
    he: 'גלה',
    ar: 'استكشف',
  },
  Saved: {
    en: 'Saved',
    de: 'Gespeichert',
    fr: 'Enregistré',
    it: 'Salvati',
    es: 'Guardado',
    pl: 'Zapisane',
    pt: 'Salvo',
    tr: 'Kaydedildi',
    ru: 'Сохранено',
    id: 'Tersimpan',
    ms: 'Disimpan',
    th: 'บันทึกแล้ว',
    vi: 'Đã lưu',
    ja: '保存済み',
    ko: '저장됨',
    zh: '已保存',
    'zh-Hant': '已儲存',
    he: 'נשמר',
    ar: 'محفوظ',
  },
  Menu: {
    en: 'Menu',
    de: 'Menü',
    fr: 'Menu',
    it: 'Menu',
    es: 'Menú',
    pl: 'Menu',
    pt: 'Menu',
    tr: 'Menü',
    ru: 'Меню',
    id: 'Menu',
    ms: 'Menu',
    th: 'เมนู',
    vi: 'Menu',
    ja: 'メニュー',
    ko: '메뉴',
    zh: '菜单',
    'zh-Hant': '選單',
    he: 'תפריט',
    ar: 'القائمة',
  },
  // Settings screens
  Settings: {
    en: 'Settings',
    de: 'Einstellungen',
    fr: 'Paramètres',
    it: 'Impostazioni',
    es: 'Ajustes',
    pl: 'Ustawienia',
    pt: 'Configurações',
    tr: 'Ayarlar',
    ru: 'Настройки',
    id: 'Pengaturan',
    ms: 'Tetapan',
    th: 'การตั้งค่า',
    vi: 'Cài đặt',
    ja: '設定',
    ko: '설정',
    zh: '设置',
    'zh-Hant': '設定',
    he: 'הגדרות',
    ar: 'الإعدادات',
  },
  Subscription: {
    en: 'Subscription',
    de: 'Abonnement',
    fr: 'Abonnement',
    it: 'Abbonamento',
    es: 'Suscripción',
    pl: 'Subskrypcja',
    pt: 'Assinatura',
    tr: 'Abonelik',
    ru: 'Подписка',
    id: 'Langganan',
    ms: 'Langganan',
    th: 'การสมัคร',
    vi: 'Gói đăng ký',
    ja: 'サブスクリプション',
    ko: '구독',
    zh: '订阅',
    'zh-Hant': '訂閱',
    he: 'מנוי',
    ar: 'الاشتراك',
  },
  Notifications: {
    en: 'Notifications',
    de: 'Benachrichtigungen',
    fr: 'Notifications',
    it: 'Notifiche',
    es: 'Notificaciones',
    pl: 'Powiadomienia',
    pt: 'Notificações',
    tr: 'Bildirimler',
    ru: 'Уведомления',
    id: 'Notifikasi',
    ms: 'Pemberitahuan',
    th: 'การแจ้งเตือน',
    vi: 'Thông báo',
    ja: '通知',
    ko: '알림',
    zh: '通知',
    'zh-Hant': '通知',
    he: 'התראות',
    ar: 'الإشعارات',
  },
  // Settings helpers & placeholders
  SubscriptionDescription: {
    en: 'Manage plans and billing.',
    de: 'Verwalte Pläne und Abrechnung.',
    fr: 'Gérez vos forfaits et votre facturation.',
    it: 'Gestisci piani e fatturazione.',
    es: 'Gestiona tus planes y facturación.',
    pl: 'Zarządzaj planami i rozliczeniami.',
    pt: 'Gerencie planos e cobranças.',
    tr: 'Planları ve faturaları yönetin.',
    ru: 'Управляйте тарифами и оплатой.',
    id: 'Kelola paket dan penagihan.',
    ms: 'Urus pelan dan pengebilan.',
    th: 'จัดการแพ็กเกจและการเรียกเก็บเงิน.',
    vi: 'Quản lý gói và thanh toán.',
    ja: 'プランと請求を管理します。',
    ko: '요금제와 결제를 관리하세요.',
    zh: '管理套餐和计费。',
    'zh-Hant': '管理方案與計費。',
    he: 'נהל את התוכניות והחיוב.',
    ar: 'إدارة الخطط والفوترة.',
  },
  NotificationsDescription: {
    en: 'Configure alerts and notification preferences.',
    de: 'Konfiguriere Benachrichtigungen und Alarme.',
    fr: 'Configurez alertes et préférences de notification.',
    it: 'Configura avvisi e preferenze di notifica.',
    es: 'Configura alertas y preferencias de notificaciones.',
    pl: 'Skonfiguruj alerty i ustawienia powiadomień.',
    pt: 'Configure alertas e preferências de notificação.',
    tr: 'Uyarıları ve bildirim tercihlerini ayarlayın.',
    ru: 'Настройте оповещения и параметры уведомлений.',
    id: 'Atur peringatan dan preferensi notifikasi.',
    ms: 'Konfigurasikan amaran dan pilihan pemberitahuan.',
    th: 'ตั้งค่าการแจ้งเตือนและการแจ้งเตือนที่ต้องการ.',
    vi: 'Cấu hình cảnh báo và tùy chọn thông báo.',
    ja: 'アラートと通知設定を構成します。',
    ko: '알림 환경설정을 구성하세요.',
    zh: '配置提醒和通知偏好设置。',
    'zh-Hant': '設定提醒與通知偏好。',
    he: 'הגדר התראות והעדפות הודעה.',
    ar: 'اضبط التنبيهات وتفضيلات الإشعارات.',
  },
  SelectASetting: {
    en: 'Select a setting…',
    de: 'Wähle eine Einstellung…',
    fr: 'Sélectionnez un réglage…',
    it: 'Seleziona un’impostazione…',
    es: 'Selecciona un ajuste…',
    pl: 'Wybierz ustawienie…',
    pt: 'Selecione uma configuração…',
    tr: 'Bir ayar seçin…',
    ru: 'Выберите параметр…',
    id: 'Pilih pengaturan…',
    ms: 'Pilih tetapan…',
    th: 'เลือกการตั้งค่า…',
    vi: 'Chọn một cài đặt…',
    ja: '設定を選択…',
    ko: '설정을 선택하세요…',
    zh: '选择一个设置…',
    'zh-Hant': '選擇一項設定…',
    he: 'בחר הגדרה…',
    ar: 'اختر إعدادًا…',
  },
  // Menu account card
  GuestUser: {
    en: 'Guest User',
    de: 'Gastbenutzer',
    fr: 'Utilisateur invité',
    it: 'Utente ospite',
    es: 'Usuario invitado',
    pl: 'Użytkownik gość',
    pt: 'Usuário convidado',
    tr: 'Misafir kullanıcı',
    ru: 'Гость',
    id: 'Pengguna tamu',
    ms: 'Pengguna tetamu',
    th: 'ผู้ใช้ชั่วคราว',
    vi: 'Người dùng khách',
    ja: 'ゲストユーザー',
    ko: '게스트 사용자',
    zh: '访客用户',
    'zh-Hant': '訪客使用者',
    he: 'משתמש אורח',
    ar: 'مستخدم ضيف',
  },
  Free: {
    en: 'FREE',
    de: 'KOSTENLOS',
    fr: 'GRATUIT',
    it: 'GRATIS',
    es: 'GRATIS',
    pl: 'DARMOWO',
    pt: 'GRÁTIS',
    tr: 'ÜCRETSİZ',
    ru: 'БЕСПЛАТНО',
    id: 'GRATIS',
    ms: 'PERCUMA',
    th: 'ฟรี',
    vi: 'MIỄN PHÍ',
    ja: '無料',
    ko: '무료',
    zh: '免费',
    'zh-Hant': '免費',
    he: 'חינם',
    ar: 'مجانًا',
  },
  Balance: {
    en: 'Balance',
    de: 'Guthaben',
    fr: 'Solde',
    it: 'Saldo',
    es: 'Saldo',
    pl: 'Saldo',
    pt: 'Saldo',
    tr: 'Bakiye',
    ru: 'Баланс',
    id: 'Saldo',
    ms: 'Baki',
    th: 'ยอดคงเหลือ',
    vi: 'Số dư',
    ja: '残高',
    ko: '잔액',
    zh: '余额',
    'zh-Hant': '餘額',
    he: 'יתרה',
    ar: 'الرصيد',
  },
  Available: {
    en: 'Available',
    de: 'Verfügbar',
    fr: 'Disponible',
    it: 'Disponibile',
    es: 'Disponible',
    pl: 'Dostępne',
    pt: 'Disponível',
    tr: 'Kullanılabilir',
    ru: 'Доступно',
    id: 'Tersedia',
    ms: 'Tersedia',
    th: 'พร้อมใช้งาน',
    vi: 'Khả dụng',
    ja: '利用可能',
    ko: '사용 가능',
    zh: '可用',
    'zh-Hant': '可用',
    he: 'זמין',
    ar: 'متاح',
  },
  AdsLeft: {
    en: 'ads left',
    de: 'Werbungen übrig',
    fr: 'annonces restantes',
    it: 'annunci rimanenti',
    es: 'anuncios restantes',
    pl: 'pozostałe reklamy',
    pt: 'anúncios restantes',
    tr: 'kalan reklam',
    ru: 'остаток объявлений',
    id: 'iklan tersisa',
    ms: 'iklan berbaki',
    th: 'โฆษณาที่เหลือ',
    vi: 'quảng cáo còn lại',
    ja: '残りの広告',
    ko: '개의 광고 남음',
    zh: '个广告剩余',
    'zh-Hant': '則廣告剩餘',
    he: 'מודעות שנותרו',
    ar: 'إعلانات متبقية',
  },
  DailyClaim: {
    en: 'Daily Claim',
    de: 'Tägliche Belohnung',
    fr: 'Récompense quotidienne',
    it: 'Ricompensa giornaliera',
    es: 'Reclamo diario',
    pl: 'Codzienna nagroda',
    pt: 'Recompensa diária',
    tr: 'Günlük ödül',
    ru: 'Ежедневный бонус',
    id: 'Klaim harian',
    ms: 'Tuntutan harian',
    th: 'รับประจำวัน',
    vi: 'Nhận thưởng hằng ngày',
    ja: 'デイリー獲得',
    ko: '일일 획득',
    zh: '每日领取',
    'zh-Hant': '每日領取',
    he: 'תביעה יומית',
    ar: 'المطالبة اليومية',
  },
  PerAd: {
    en: 'Per Ad',
    de: 'pro Anzeige',
    fr: 'par annonce',
    it: 'per annuncio',
    es: 'Por anuncio',
    pl: 'na reklamę',
    pt: 'por anúncio',
    tr: 'reklam başına',
    ru: 'за объявление',
    id: 'per iklan',
    ms: 'setiap iklan',
    th: 'ต่อโฆษณา',
    vi: 'mỗi quảng cáo',
    ja: '広告あたり',
    ko: '광고당',
    zh: '每条广告',
    'zh-Hant': '每則廣告',
    he: 'למודעה',
    ar: 'لكل إعلان',
  },
  MaxPerDay: {
    en: 'Max/Day',
    de: 'Max/Tag',
    fr: 'Max/jour',
    it: 'Max/giorno',
    es: 'Máx/día',
    pl: 'Maks/dzień',
    pt: 'Máx/dia',
    tr: 'Günlük en fazla',
    ru: 'Макс/день',
    id: 'Maks/hari',
    ms: 'Maks/hari',
    th: 'สูงสุด/วัน',
    vi: 'Tối đa/ngày',
    ja: '1日の上限',
    ko: '하루 최대',
    zh: '每日上限',
    'zh-Hant': '每日上限',
    he: 'מקסימום/יום',
    ar: 'الحد الأقصى/اليوم',
  },
  ClaimDaily: {
    en: 'Claim Daily',
    de: 'Täglich abholen',
    fr: 'Réclamer chaque jour',
    it: 'Riscatta ogni giorno',
    es: 'Reclamar diario',
    pl: 'Odbieraj codziennie',
    pt: 'Resgatar diariamente',
    tr: 'Her gün al',
    ru: 'Получайте каждый день',
    id: 'Klaim setiap hari',
    ms: 'Tuntut setiap hari',
    th: 'รับทุกวัน',
    vi: 'Nhận mỗi ngày',
    ja: '毎日受け取る',
    ko: '매일 받기',
    zh: '每日领取',
    'zh-Hant': '每日領取',
    he: 'קבל יום-יום',
    ar: 'احصل يوميًا',
  },
  WatchAndEarn: {
    en: 'Watch & Earn',
    de: 'Schau & verdiene',
    fr: 'Regarder et gagner',
    it: 'Guarda e guadagna',
    es: 'Ver y ganar',
    pl: 'Oglądaj i zarabiaj',
    pt: 'Assista e ganhe',
    tr: 'İzle ve kazan',
    ru: 'Смотри и заработай',
    id: 'Tonton & dapatkan',
    ms: 'Tonton & jana',
    th: 'ดูแล้วรับ',
    vi: 'Xem và nhận thưởng',
    ja: '見て稼ぐ',
    ko: '보고 적립',
    zh: '观看赚取',
    'zh-Hant': '觀看賺取',
    he: 'צפה והרוויח',
    ar: 'شاهد واربح',
  },
  // Other screens
  About: {
    en: 'About',
    de: 'Info',
    fr: 'À propos',
    it: 'Informazioni',
    es: 'Acerca de',
    pl: 'Informacje',
    pt: 'Sobre',
    tr: 'Hakkında',
    ru: 'О приложении',
    id: 'Tentang',
    ms: 'Perihal',
    th: 'เกี่ยวกับ',
    vi: 'Giới thiệu',
    ja: '情報',
    ko: '정보',
    zh: '关于',
    'zh-Hant': '關於',
    he: 'אודות',
    ar: 'حول',
  },
  PrivacyPolicy: {
    en: 'Privacy Policy',
    de: 'Datenschutzrichtlinie',
    fr: 'Politique de confidentialité',
    it: 'Informativa sulla privacy',
    es: 'Política de privacidad',
    pl: 'Polityka prywatności',
    pt: 'Política de privacidade',
    tr: 'Gizlilik politikası',
    ru: 'Политика конфиденциальности',
    id: 'Kebijakan privasi',
    ms: 'Dasar privasi',
    th: 'นโยบายความเป็นส่วนตัว',
    vi: 'Chính sách quyền riêng tư',
    ja: 'プライバシーポリシー',
    ko: '개인정보 처리방침',
    zh: '隐私政策',
    'zh-Hant': '隱私政策',
    he: 'מדיניות פרטיות',
    ar: 'سياسة الخصوصية',
  },
  TermsOfUse: {
    en: 'Terms of Use',
    de: 'Nutzungsbedingungen',
    fr: "Conditions d'utilisation",
    it: "Termini d'uso",
    es: 'Términos de uso',
    pl: 'Warunki korzystania',
    pt: 'Termos de uso',
    tr: 'Kullanım koşulları',
    ru: 'Условия использования',
    id: 'Ketentuan penggunaan',
    ms: 'Syarat penggunaan',
    th: 'ข้อกำหนดการใช้งาน',
    vi: 'Điều khoản sử dụng',
    ja: '利用規約',
    ko: '이용 약관',
    zh: '使用条款',
    'zh-Hant': '使用條款',
    he: 'תנאי שימוש',
    ar: 'شروط الاستخدام',
  },
  Activity: {
    en: 'Activity',
    de: 'Aktivität',
    fr: 'Activité',
    it: 'Attività',
    es: 'Actividad',
    pl: 'Aktywność',
    pt: 'Atividade',
    tr: 'Etkinlik',
    ru: 'Активность',
    id: 'Aktivitas',
    ms: 'Aktiviti',
    th: 'กิจกรรม',
    vi: 'Hoạt động',
    ja: 'アクティビティ',
    ko: '활동',
    zh: '活动',
    'zh-Hant': '活動',
    he: 'פעילות',
    ar: 'النشاط',
  },
  Portfolio: {
    en: 'Portfolio',
    de: 'Portfolio',
    fr: 'Portefeuille',
    it: 'Portafoglio',
    es: 'Portafolio',
    pl: 'Portfel',
    pt: 'Portfólio',
    tr: 'Portföy',
    ru: 'Портфель',
    id: 'Portofolio',
    ms: 'Portfolio',
    th: 'พอร์ตโฟลิโอ',
    vi: 'Danh mục',
    ja: 'ポートフォリオ',
    ko: '포트폴리오',
    zh: '投资组合',
    'zh-Hant': '投資組合',
    he: 'תיק השקעות',
    ar: 'المحفظة',
  },
  Support: {
    en: 'Support',
    de: 'Support',
    fr: 'Support',
    it: 'Supporto',
    es: 'Soporte',
    pl: 'Wsparcie',
    pt: 'Suporte',
    tr: 'Destek',
    ru: 'Поддержка',
    id: 'Dukungan',
    ms: 'Sokongan',
    th: 'ฝ่ายสนับสนุน',
    vi: 'Hỗ trợ',
    ja: 'サポート',
    ko: '지원',
    zh: '支持',
    'zh-Hant': '支援',
    he: 'תמיכה',
    ar: 'الدعم',
  },
  ReportProblem: {
    en: 'Report a problem',
    de: 'Problem melden',
    fr: 'Signaler un problème',
    it: 'Segnala un problema',
    es: 'Informar un problema',
    pl: 'Zgłoś problem',
    pt: 'Relatar um problema',
    tr: 'Sorun bildir',
    ru: 'Сообщить о проблеме',
    id: 'Laporkan masalah',
    ms: 'Laporkan masalah',
    th: 'รายงานปัญหา',
    vi: 'Báo lỗi',
    ja: '問題を報告',
    ko: '문제 신고',
    zh: '报告问题',
    'zh-Hant': '回報問題',
    he: 'דווח על בעיה',
    ar: 'أبلغ عن مشكلة',
  },
  PrivacySecurityHelp: {
    en: 'Privacy & Security Help',
    de: 'Hilfe zu Datenschutz & Sicherheit',
    fr: 'Aide sur la confidentialité et la sécurité',
    it: 'Aiuto su privacy e sicurezza',
    es: 'Ayuda de privacidad y seguridad',
    pl: 'Pomoc w zakresie prywatności i bezpieczeństwa',
    pt: 'Ajuda de privacidade e segurança',
    tr: 'Gizlilik ve Güvenlik Yardımı',
    ru: 'Помощь по конфиденциальности и безопасности',
    id: 'Bantuan privasi & keamanan',
    ms: 'Bantuan privasi & keselamatan',
    th: 'ความช่วยเหลือด้านความเป็นส่วนตัวและความปลอดภัย',
    vi: 'Trợ giúp về quyền riêng tư và bảo mật',
    ja: 'プライバシーとセキュリティのヘルプ',
    ko: '개인정보 및 보안 도움말',
    zh: '隐私与安全帮助',
    'zh-Hant': '隱私與安全協助',
    he: 'עזרה בפרטיות ואבטחה',
    ar: 'مساعدة الخصوصية والأمان',
  },
  HelpCenter: {
    en: 'Help Center',
    de: 'Hilfe-Center',
    fr: "Centre d'aide",
    it: 'Centro assistenza',
    es: 'Centro de ayuda',
    pl: 'Centrum pomocy',
    pt: 'Central de ajuda',
    tr: 'Yardım merkezi',
    ru: 'Справочный центр',
    id: 'Pusat bantuan',
    ms: 'Pusat bantuan',
    th: 'ศูนย์ช่วยเหลือ',
    vi: 'Trung tâm trợ giúp',
    ja: 'ヘルプセンター',
    ko: '도움말 센터',
    zh: '帮助中心',
    'zh-Hant': '說明中心',
    he: 'מרכז העזרה',
    ar: 'مركز المساعدة',
  },
  Watchlists: {
    en: 'Watchlists',
    de: 'Beobachtungslisten',
    fr: 'Listes de suivi',
    it: 'Liste di osservazione',
    es: 'Listas de seguimiento',
    pl: 'Listy obserwowanych',
    pt: 'Listas de observação',
    tr: 'İzleme listeleri',
    ru: 'Списки наблюдения',
    id: 'Daftar pantau',
    ms: 'Senarai pantau',
    th: 'รายการเฝ้าดู',
    vi: 'Danh sách theo dõi',
    ja: 'ウォッチリスト',
    ko: '관심목록',
    zh: '关注列表',
    'zh-Hant': '觀察清單',
    he: 'רשימות מעקב',
    ar: 'قوائم المراقبة',
  },
  // WatchlistsDescription already expanded later
  YourActivity: {
    en: 'Your Activity',
    de: 'Deine Aktivität',
    fr: 'Votre activité',
    it: 'La tua attività',
    es: 'Tu actividad',
    pl: 'Twoja aktywność',
    pt: 'Sua atividade',
    tr: 'Aktiviten',
    ru: 'Ваша активность',
    id: 'Aktivitas Anda',
    ms: 'Aktiviti anda',
    th: 'กิจกรรมของคุณ',
    vi: 'Hoạt động của bạn',
    ja: 'あなたのアクティビティ',
    ko: '내 활동',
    zh: '你的活动',
    'zh-Hant': '你的活動',
    he: 'הפעילות שלך',
    ar: 'نشاطك',
  },
  Likes: {
    en: 'Likes',
    de: 'Gefällt mir',
    fr: 'Mentions J’aime',
    it: 'Mi piace',
    es: 'Me gusta',
    pl: 'Polubienia',
    pt: 'Curtidas',
    tr: 'Beğeniler',
    ru: 'Лайки',
    id: 'Suka',
    ms: 'Suka',
    th: 'ถูกใจ',
    vi: 'Lượt thích',
    ja: 'いいね',
    ko: '좋아요',
    zh: '点赞',
    'zh-Hant': '按讚',
    he: 'לייקים',
    ar: 'إعجابات',
  },
  Comments: {
    en: 'Comments',
    de: 'Kommentare',
    fr: 'Commentaires',
    it: 'Commenti',
    es: 'Comentarios',
    pl: 'Komentarze',
    pt: 'Comentários',
    tr: 'Yorumlar',
    ru: 'Комментарии',
    id: 'Komentar',
    ms: 'Komen',
    th: 'ความคิดเห็น',
    vi: 'Bình luận',
    ja: 'コメント',
    ko: '댓글',
    zh: '评论',
    'zh-Hant': '留言',
    he: 'תגובות',
    ar: 'تعليقات',
  },
  Reposts: {
    en: 'Reposts',
    de: 'Geteilte Beiträge',
    fr: 'Partages',
    it: 'Ripubblicazioni',
    es: 'Reposts',
    pl: 'Udostępnienia',
    pt: 'Reposts',
    tr: 'Yeniden paylaşımlar',
    ru: 'Репосты',
    id: 'Repost',
    ms: 'Siarkan semula',
    th: 'การรีโพสต์',
    vi: 'Chia sẻ lại',
    ja: 'リポスト',
    ko: '리포스트',
    zh: '转发',
    'zh-Hant': '轉發',
    he: 'שיתופים מחדש',
    ar: 'إعادات نشر',
  },
  WatchedStocks: {
    en: 'Recently Watched Coins',
    de: 'Kürzlich angesehene Aktien',
    fr: 'Actions consultées récemment',
    it: 'Titoli guardati di recente',
    es: 'Acciones vistas recientemente',
    pl: 'Ostatnio oglądane akcje',
    pt: 'Ações vistas recentemente',
    tr: 'Yakın zamanda izlenen hisseler',
    ru: 'Недавно просмотренные акции',
    id: 'Saham yang baru dilihat',
    ms: 'Saham yang baru dilihat',
    th: 'หุ้นที่ดูล่าสุด',
    vi: 'Cổ phiếu đã xem gần đây',
    ja: '最近見た株',
    ko: '최근 확인한 주식',
    zh: '最近查看的股票',
    'zh-Hant': '最近查看的股票',
    he: 'מניות שנצפו לאחרונה',
    ar: 'الأسهم التي تمت مشاهدتها مؤخرًا',
  },
  AccountHistory: {
    en: 'Account History',
    de: 'Kontoverlauf',
    fr: 'Historique du compte',
    it: 'Cronologia conto',
    es: 'Historial de cuenta',
    pl: 'Historia konta',
    pt: 'Histórico da conta',
    tr: 'Hesap geçmişi',
    ru: 'История аккаунта',
    id: 'Riwayat akun',
    ms: 'Sejarah akaun',
    th: 'ประวัติบัญชี',
    vi: 'Lịch sử tài khoản',
    ja: 'アカウント履歴',
    ko: '계정 기록',
    zh: '账户历史',
    'zh-Hant': '帳戶歷史',
    he: 'היסטוריית חשבון',
    ar: 'سجل الحساب',
  },
  RecentSearches: {
    en: 'Recent Searches',
    de: 'Letzte Suchanfragen',
    fr: 'Recherches récentes',
    it: 'Ricerche recenti',
    es: 'Búsquedas recientes',
    pl: 'Ostatnie wyszukiwania',
    pt: 'Pesquisas recentes',
    tr: 'Son aramalar',
    ru: 'Недавние поиски',
    id: 'Pencarian terbaru',
    ms: 'Carian terkini',
    th: 'การค้นหาล่าสุด',
    vi: 'Tìm kiếm gần đây',
    ja: '最近の検索',
    ko: '최근 검색',
    zh: '最近搜索',
    'zh-Hant': '最近搜尋',
    he: 'חיפושים אחרונים',
    ar: 'أحدث عمليات البحث',
  },
  // Scouters screen
  ScoutersHeader: {
    en: 'Scouters',
    de: 'Scouter',
    fr: 'Éclaireurs',
    it: 'Scout',
    es: 'Exploradores',
    pl: 'Zwiadowcy',
    pt: 'Exploradores',
    tr: 'Keşifçiler',
    ru: 'Скауты',
    id: 'Pengintai',
    ms: 'Peninjau',
    th: 'สเกาต์',
    vi: 'Trinh sát',
    ja: 'スカウター',
    ko: '스카우터',
    zh: '侦察',
    'zh-Hant': '偵察',
    he: 'צופים',
    ar: 'الكشافة',
  },
  ScoutersSubtitle: {
    en: 'Live market signals built from the current feed.',
    de: 'Erstelle und verwalte deine Scouter.',
    fr: 'Créez et gérez vos éclaireurs.',
    it: 'Crea e gestisci i tuoi scout.',
    es: 'Crea y gestiona tus exploradores.',
    pl: 'Twórz i zarządzaj zwiadowcami.',
    pt: 'Crie e gerencie seus exploradores.',
    tr: 'Keşif ekiplerini oluşturup yönetin.',
    ru: 'Создавайте и управляйте своими скаутами.',
    id: 'Buat dan kelola scouter Anda.',
    ms: 'Cipta dan urus peninjau anda.',
    th: 'สร้างและจัดการทีมสเกาต์ของคุณ',
    vi: 'Tạo và quản lý đội trinh sát của bạn.',
    ja: 'スカウターを作成・管理します。',
    ko: '스카우터를 생성하고 관리하세요.',
    zh: '创建并管理你的侦察器。',
    'zh-Hant': '建立並管理您的偵察器。',
    he: 'צור ונהל את הסקאוטרים שלך.',
    ar: 'أنشئ كشافتك وأدرها.',
  },
  RecentMatches: {
    en: 'Signal snapshot',
    de: 'Neueste配对',
    fr: 'Correspondances récentes',
    it: 'Match recenti',
    es: 'Coincidencias recientes',
    pl: 'Ostatnie dopasowania',
    pt: 'Partidas recentes',
    tr: 'Son eşleşmeler',
    ru: 'Недавние совпадения',
    id: 'Kecocokan terbaru',
    ms: 'Padanan terkini',
    th: 'การจับคู่ล่าสุด',
    vi: 'Kết quả gần đây',
    ja: '最近のマッチ',
    ko: '최근 매치',
    zh: '最新匹配',
    'zh-Hant': '最新配對',
    he: 'התאמות אחרונות',
    ar: 'المطابقات الأخيرة',
  },
  CreateNewScouter: {
    en: 'Create New Scouter',
    de: 'Neuen Scouter erstellen',
    fr: 'Créer un nouvel éclaireur',
    it: 'Crea un nuovo scout',
    es: 'Crear nuevo explorador',
    pl: 'Utwórz nowego zwiadowcę',
    pt: 'Criar novo explorador',
    tr: 'Yeni keşifçi oluştur',
    ru: 'Создайте нового скаута',
    id: 'Buat scouter baru',
    ms: 'Cipta peninjau baharu',
    th: 'สร้างสเกาต์ใหม่',
    vi: 'Tạo scouter mới',
    ja: '新しいスカウターを作成',
    ko: '새 스카우터 만들기',
    zh: '创建新侦察器',
    'zh-Hant': '建立新的偵察器',
    he: 'צור סקאוטר חדש',
    ar: 'أنشئ كشافًا جديدًا',
  },
  YourScouters: {
    en: 'Your Scouters',
    de: 'Deine Scouter',
    fr: 'Vos éclaireurs',
    it: 'I tuoi scout',
    es: 'Tus exploradores',
    pl: 'Twoi zwiadowcy',
    pt: 'Seus exploradores',
    tr: 'Keşifçilerin',
    ru: 'Ваши скауты',
    id: 'Scouter Anda',
    ms: 'Peninjau anda',
    th: 'สเกาต์ของคุณ',
    vi: 'Đội trinh sát của bạn',
    ja: 'あなたのスカウター',
    ko: '내 스카우터',
    zh: '你的侦察器',
    'zh-Hant': '你的偵察器',
    he: 'הסקאוטרים שלך',
    ar: 'كشافوك',
  },
  LastRun: {
    en: 'Last run',
    de: 'Letzter przebieg',
    fr: 'Dernière exécution',
    it: "Ultima esecuzione",
    es: 'Última ejecución',
    pl: 'Ostatnie uruchomienie',
    pt: 'Última execução',
    tr: 'Son çalıştırma',
    ru: 'Последний запуск',
    id: 'Terakhir dijalankan',
    ms: 'Larian terakhir',
    th: 'รันล่าสุด',
    vi: 'Lần chạy gần đây',
    ja: '最終実行',
    ko: '마지막 실행',
    zh: '上次运行',
    'zh-Hant': '上次執行',
    he: 'הרצה אחרונה',
    ar: 'آخر تشغيل',
  },
  Active: {
    en: 'Live',
    de: 'Aktiv',
    fr: 'Actif',
    it: 'Attivo',
    es: 'Activo',
    pl: 'Aktywny',
    pt: 'Ativo',
    tr: 'Aktif',
    ru: 'Активен',
    id: 'Aktif',
    ms: 'Aktif',
    th: 'ใช้งานอยู่',
    vi: 'Hoạt động',
    ja: '有効',
    ko: '활성',
    zh: '启用',
    'zh-Hant': '啟用',
    he: 'פעיל',
    ar: 'نشط',
  },
  Paused: {
    en: 'Paused',
    de: 'Pausiert',
    fr: 'En pause',
    it: 'In pausa',
    es: 'Pausado',
    pl: 'Wstrzymany',
    pt: 'Pausado',
    tr: 'Duraklatıldı',
    ru: 'Приостановлено',
    id: 'Dijeda',
    ms: 'Dijeda',
    th: 'หยุดชั่วคราว',
    vi: 'Tạm dừng',
    ja: '一時停止',
    ko: '일시정지',
    zh: '已暂停',
    'zh-Hant': '已暫停',
    he: 'מושהה',
    ar: 'متوقّف مؤقتًا',
  },
  MatchesToday: {
    en: 'matches today',
    de: 'Treffer heute',
    fr: 'correspondances aujourd’hui',
    it: 'corrispondenze oggi',
    es: 'coincidencias hoy',
    pl: 'dopasowania dziś',
    pt: 'combinações de hoje',
    tr: 'bugünkü eşleşmeler',
    ru: 'совпадений сегодня',
    id: 'kecocokan hari ini',
    ms: 'padanan hari ini',
    th: 'การจับคู่วันนี้',
    vi: 'phù hợp hôm nay',
    ja: '件のマッチ',
    ko: '건 매치',
    zh: '今日匹配',
    'zh-Hant': '今日配對',
    he: 'התאמות היום',
    ar: 'مطابقات اليوم',
  },
  RunNow: {
    en: 'Run Now',
    de: 'Jetzt starten',
    fr: 'Exécuter maintenant',
    it: 'Esegui ora',
    es: 'Ejecutar ahora',
    pl: 'Uruchom teraz',
    pt: 'Executar agora',
    tr: 'Şimdi çalıştır',
    ru: 'Запустить сейчас',
    id: 'Jalankan sekarang',
    ms: 'Jalankan sekarang',
    th: 'เรียกใช้ตอนนี้',
    vi: 'Chạy ngay',
    ja: '今すぐ実行',
    ko: '지금 실행',
    zh: '立即运行',
    'zh-Hant': '立即執行',
    he: 'הרץ עכשיו',
    ar: 'تشغيل الآن',
  },
  Edit: {
    en: 'Edit',
    de: 'Bearbeiten',
    fr: 'Modifier',
    it: 'Modifica',
    es: 'Editar',
    pl: 'Edytuj',
    pt: 'Editar',
    tr: 'Düzenle',
    ru: 'Редактировать',
    id: 'Edit',
    ms: 'Sunting',
    th: 'แก้ไข',
    vi: 'Chỉnh sửa',
    ja: '編集',
    ko: '편집',
    zh: '编辑',
    'zh-Hant': '編輯',
    he: 'ערוך',
    ar: 'تحرير',
  },
  PopularTemplates: {
    en: 'Popular Templates',
    de: 'Beliebte Vorlagen',
    fr: 'Modèles populaires',
    it: 'Modelli popolari',
    es: 'Plantillas populares',
    pl: 'Popularne szablony',
    pt: 'Modelos populares',
    tr: 'Popüler şablonlar',
    ru: 'Популярные шаблоны',
    id: 'Template populer',
    ms: 'Templat popular',
    th: 'เทมเพลตยอดนิยม',
    vi: 'Mẫu phổ biến',
    ja: '人気のテンプレート',
    ko: '인기 템플릿',
    zh: '热门模板',
    'zh-Hant': '熱門模板',
    he: 'תבניות פופולריות',
    ar: 'القوالب الشائعة',
  },
  // Explore screen
  ExploreHeader: {
    en: 'Explore',
    de: 'Entdecken',
    fr: 'Explorer',
    it: 'Esplora',
    es: 'Explorar',
    pl: 'Odkrywaj',
    pt: 'Explorar',
    tr: 'Keşfet',
    ru: 'Исследовать',
    id: 'Jelajahi',
    ms: 'Teroka',
    th: 'สำรวจ',
    vi: 'Khám phá',
    ja: '探索',
    ko: '탐색',
    zh: '探索',
    'zh-Hant': '探索',
    he: 'גלה',
    ar: 'استكشف',
  },
  USStocks: {
    en: 'US Markets',
    de: 'US-Aktien',
    fr: 'Actions américaines',
    it: 'Azioni USA',
    es: 'Acciones EE. UU.',
    pl: 'Akcje USA',
    pt: 'Ações dos EUA',
    tr: 'ABD Hisseleri',
    ru: 'Акции США',
    id: 'Saham AS',
    ms: 'Saham AS',
    th: 'หุ้นสหรัฐฯ',
    vi: 'Cổ phiếu Mỹ',
    ja: '米国株',
    ko: '미국 주식',
    zh: '美股',
    'zh-Hant': '美股',
    he: 'מניות ארה"ב',
    ar: 'الأسهم الأمريكية',
  },
  Coins: {
    en: 'Coins',
    de: 'Kryptomünzen',
    fr: 'Cryptomonnaies',
    it: 'Criptovalute',
    es: 'Monedas',
    pl: 'Kryptowaluty',
    pt: 'Moedas digitais',
    tr: 'Kripto Paralar',
    ru: 'Криптовалюты',
    id: 'Koin Kripto',
    ms: 'Syiling Kripto',
    th: 'คริปโต',
    vi: 'Tiền mã hóa',
    ja: 'コイン',
    ko: '코인',
    zh: '币种',
    'zh-Hant': '幣種',
    he: 'מטבעות',
    ar: 'عملات رقمية',
  },
  Bonds: {
    en: 'Bonds',
    de: 'Anleihen',
    fr: 'Obligations',
    it: 'Obbligazioni',
    es: 'Bonos',
    pl: 'Obligacje',
    pt: 'Títulos',
    tr: 'Tahviller',
    ru: 'Облигации',
    id: 'Obligasi',
    ms: 'Bon',
    th: 'พันธบัตร',
    vi: 'Trái phiếu',
    ja: '債券',
    ko: '채권',
    zh: '债券',
    'zh-Hant': '債券',
    he: 'אג"ח',
    ar: 'سندات',
  },
  ETF: {
    en: 'ETF',
    de: 'ETF',
    fr: 'ETF',
    it: 'ETF',
    es: 'ETF',
    pl: 'ETF',
    pt: 'ETF',
    tr: 'ETF',
    ru: 'ETF',
    id: 'ETF',
    ms: 'ETF',
    th: 'กองทุน ETF',
    vi: 'ETF',
    ja: 'ETF',
    ko: 'ETF',
    zh: 'ETF',
    'zh-Hant': 'ETF',
    he: 'תעודות סל',
    ar: 'صناديق المؤشرات المتداولة',
  },
  LiveStocks: {
    en: 'Live Coins',
    de: 'Live-Aktien',
    fr: 'Actions en direct',
    it: 'Titoli in tempo reale',
    es: 'Acciones en vivo',
    pl: 'Akcje na żywo',
    pt: 'Ações em tempo real',
    tr: 'Canlı Hisseler',
    ru: 'Акции в реальном времени',
    id: 'Saham Langsung',
    ms: 'Saham Langsung',
    th: 'หุ้นสด',
    vi: 'Cổ phiếu trực tiếp',
    ja: 'ライブ株式',
    ko: '실시간 주식',
    zh: '实时股票',
    'zh-Hant': '即時股票',
    he: 'מניות חיות',
    ar: 'أسهم مباشرة',
  },
  Volume: {
    en: 'Volume',
    de: 'Volumen',
    fr: 'Volume',
    it: 'Volume',
    es: 'Volumen',
    pl: 'Wolumen',
    pt: 'Volume',
    tr: 'Hacim',
    ru: 'Объём',
    id: 'Volume',
    ms: 'Volum',
    th: 'ปริมาณ',
    vi: 'Khối lượng',
    ja: '出来高',
    ko: '거래량',
    zh: '成交量',
    'zh-Hant': '成交量',
    he: 'נפח',
    ar: 'حجم التداول',
  },
  TradesCount: {
    en: '# Trades',
    de: 'Anz. Trades',
    fr: 'Nbre opérations',
    it: 'N. scambi',
    es: '# Operaciones',
    pl: 'Liczba transakcji',
    pt: 'Qtd. negociações',
    tr: 'İşlem adedi',
    ru: 'Кол-во сделок',
    id: 'Jumlah transaksi',
    ms: 'Bil. dagangan',
    th: 'จำนวนเทรด',
    vi: 'Số giao dịch',
    ja: '取引数',
    ko: '거래 수',
    zh: '交易数',
    'zh-Hant': '交易數',
    he: 'מספר עסקאות',
    ar: 'عدد الصفقات',
  },
  Gainers: {
    en: 'Gainers',
    de: 'Gewinner',
    fr: 'Hausse',
    it: 'Rialzi',
    es: 'Ganadoras',
    pl: 'Zwyżkujące',
    pt: 'Em alta',
    tr: 'Yükselenler',
    ru: 'Лидеры роста',
    id: 'Penguat',
    ms: 'Pengukuh',
    th: 'หุ้นขึ้น',
    vi: 'Tăng mạnh',
    ja: '上昇',
    ko: '급상승',
    zh: '涨幅',
    'zh-Hant': '漲幅',
    he: 'עולות',
    ar: 'المرتفعة',
  },
  Losers: {
    en: 'Losers',
    de: 'Verlierer',
    fr: 'Baisse',
    it: 'Ribassi',
    es: 'Perdedoras',
    pl: 'Spadki',
    pt: 'Em queda',
    tr: 'Düşenler',
    ru: 'Лидеры падения',
    id: 'Pelemah',
    ms: 'Menurun',
    th: 'หุ้นลง',
    vi: 'Giảm mạnh',
    ja: '下落',
    ko: '급하락',
    zh: '跌幅',
    'zh-Hant': '跌幅',
    he: 'יורדות',
    ar: 'المنخفضة',
  },
  Popular: {
    en: 'Popular',
    de: 'Beliebt',
    fr: 'Populaire',
    it: 'Popolari',
    es: 'Populares',
    pl: 'Popularne',
    pt: 'Populares',
    tr: 'Popüler',
    ru: 'Популярное',
    id: 'Populer',
    ms: 'Popular',
    th: 'ยอดนิยม',
    vi: 'Phổ biến',
    ja: '人気',
    ko: '인기',
    zh: '热门',
    'zh-Hant': '熱門',
    he: 'פופולרי',
    ar: 'شائع',
  },
  More: {
    en: 'More',
    de: 'Mehr',
    fr: 'Plus',
    it: 'Altro',
    es: 'Más',
    pl: 'Więcej',
    pt: 'Mais',
    tr: 'Daha fazla',
    ru: 'Еще',
    id: 'Lainnya',
    ms: 'Lagi',
    th: 'เพิ่มเติม',
    vi: 'Thêm',
    ja: 'もっと見る',
    ko: '더보기',
    zh: '更多',
    'zh-Hant': '更多',
    he: 'עוד',
    ar: 'المزيد',
  },
  UpcomingReports: {
    en: 'Upcoming Reports',
    de: 'Bevorstehende Berichte',
    fr: 'Rapports à venir',
    it: 'Prossimi report',
    es: 'Próximos informes',
    pl: 'Nadchodzące raporty',
    pt: 'Relatórios futuros',
    tr: 'Yaklaşan raporlar',
    ru: 'Предстоящие отчёты',
    id: 'Laporan mendatang',
    ms: 'Laporan akan datang',
    th: 'รายงานที่กำลังจะออก',
    vi: 'Báo cáo sắp tới',
    ja: '今後の決算',
    ko: '다가오는 실적',
    zh: '即将发布的报告',
    'zh-Hant': '即將發布的報告',
    he: 'דוחות קרובים',
    ar: 'التقارير القادمة',
  },
  HotCommunityPosts: {
    en: 'Hot Community Posts',
    de: 'Beliebte Community-Beiträge',
    fr: 'Publications populaires',
    it: 'Post popolari della community',
    es: 'Publicaciones populares',
    pl: 'Gorące wpisy społeczności',
    pt: 'Publicações populares da comunidade',
    tr: 'Popüler topluluk gönderileri',
    ru: 'Популярные посты сообщества',
    id: 'Posting komunitas terpopuler',
    ms: 'Catatan komuniti popular',
    th: 'โพสต์ยอดฮิตในชุมชน',
    vi: 'Bài viết cộng đồng nổi bật',
    ja: '人気の投稿',
    ko: '인기 커뮤니티 글',
    zh: '热门帖子',
    'zh-Hant': '熱門貼文',
    he: 'פוסטים חמים בקהילה',
    ar: 'منشورات المجتمع الرائجة',
  },
  // Settings search
  SettingsSearchPlaceholder: {
    en: 'Search settings, help, features...',
    de: 'Einstellungen, Hilfe, Funktionen suchen…',
    fr: 'Rechercher réglages, aide, fonctionnalités…',
    it: 'Cerca impostazioni, aiuto, funzioni…',
    es: 'Buscar ajustes, ayuda, funciones…',
    pl: 'Szukaj ustawień, pomocy, funkcji…',
    pt: 'Pesquisar definições, ajuda, funcionalidades…',
    tr: 'Ayarları, yardımı, özellikleri ara…',
    ru: 'Искать настройки, справку, функции…',
    id: 'Cari pengaturan, bantuan, fitur…',
    ms: 'Cari tetapan, bantuan, ciri…',
    th: 'ค้นหาการตั้งค่า ความช่วยเหลือ ฟีเจอร์…',
    vi: 'Tìm kiếm cài đặt, trợ giúp, tính năng…',
    ja: '設定・ヘルプ・機能を検索…',
    ko: '설정, 도움말, 기능 검색…',
    zh: '搜索设置、帮助、功能…',
    'zh-Hant': '搜尋設定、說明、功能…',
    he: 'חיפוש הגדרות, עזרה, תכונות…',
    ar: 'ابحث عن الإعدادات، المساعدة، الميزات…',
  },
  // Saved screen
  SavedHeader: {
    en: 'Saved',
    de: 'Gespeichert',
    fr: 'Enregistré',
    it: 'Salvati',
    es: 'Guardado',
    pl: 'Zapisane',
    pt: 'Salvo',
    tr: 'Kaydedildi',
    ru: 'Сохранено',
    id: 'Tersimpan',
    ms: 'Disimpan',
    th: 'บันทึกแล้ว',
    vi: 'Đã lưu',
    ja: '保存済み',
    ko: '저장됨',
    zh: '已保存',
    'zh-Hant': '已儲存',
    he: 'נשמר',
    ar: 'محفوظ',
  },
  SavedSubtitle: {
    en: 'Your saved lists and watchlists.',
    de: 'Deine gespeicherten Listen und Watchlists.',
    fr: 'Vos listes et listes de suivi enregistrées.',
    it: 'Le tue liste e watchlist salvate.',
    es: 'Tus listas y vigilados guardados.',
    pl: 'Twoje zapisane listy i listy obserwowanych.',
    pt: 'Suas listas e listas de observação salvas.',
    tr: 'Kaydedilen listelerin ve izleme listelerin.',
    ru: 'Ваши сохранённые списки и списки отслеживания.',
    id: 'Daftar dan watchlist tersimpan Anda.',
    ms: 'Senarai dan senarai tontonan yang anda simpan.',
    th: 'รายการและเฝ้าดูที่คุณบันทึกไว้',
    vi: 'Danh sách và danh mục theo dõi đã lưu của bạn.',
    ja: '保存したリストとウォッチリストです。',
    ko: '저장한 목록과 관심목록입니다.',
    zh: '你保存的列表与关注列表。',
    'zh-Hant': '您儲存的列表與自選。',
    he: 'הרשימות ורשימות המעקב ששמרת.',
    ar: 'القوائم وقوائم المراقبة التي حفظتها.',
  },
  Stocks: {
    en: 'Coins',
    de: 'Aktien',
    fr: 'Actions',
    it: 'Azioni',
    es: 'Acciones',
    pl: 'Akcje',
    pt: 'Ações',
    tr: 'Hisseler',
    ru: 'Акции',
    id: 'Saham',
    ms: 'Saham',
    th: 'หุ้น',
    vi: 'Cổ phiếu',
    ja: '株式',
    ko: '주식',
    zh: '股票',
    'zh-Hant': '股票',
    he: 'מניות',
    ar: 'الأسهم',
  },
  Posts: {
    en: 'Posts',
    de: 'Beiträge',
    fr: 'Publications',
    it: 'Post',
    es: 'Publicaciones',
    pl: 'Posty',
    pt: 'Publicações',
    tr: 'Gönderiler',
    ru: 'Публикации',
    id: 'Posting',
    ms: 'Catatan',
    th: 'โพสต์',
    vi: 'Bài viết',
    ja: '投稿',
    ko: '게시물',
    zh: '帖子',
    'zh-Hant': '貼文',
    he: 'פוסטים',
    ar: 'المنشورات',
  },
  SavedPosts: {
    en: 'Saved Posts',
    de: 'Gespeicherte Beiträge',
    fr: 'Publications enregistrées',
    it: 'Post salvati',
    es: 'Publicaciones guardadas',
    pl: 'Zapisane posty',
    pt: 'Publicações salvas',
    tr: 'Kaydedilen gönderiler',
    ru: 'Сохранённые публикации',
    id: 'Posting tersimpan',
    ms: 'Catatan disimpan',
    th: 'โพสต์ที่บันทึกไว้',
    vi: 'Bài viết đã lưu',
    ja: '保存した投稿',
    ko: '저장된 게시물',
    zh: '已保存的帖子',
    'zh-Hant': '已儲存的貼文',
    he: 'פוסטים שמורים',
    ar: 'المنشورات المحفوظة',
  },
  RecentlyViewed: {
    en: 'Recently Viewed',
    de: 'Zuletzt angesehen',
    fr: 'Consulté récemment',
    it: 'Visti di recente',
    es: 'Visto recientemente',
    pl: 'Ostatnio oglądane',
    pt: 'Visto recentemente',
    tr: 'Son bakılanlar',
    ru: 'Недавно просмотренные',
    id: 'Baru dilihat',
    ms: 'Baru dilihat',
    th: 'ดูล่าสุด',
    vi: 'Xem gần đây',
    ja: '最近見た項目',
    ko: '최근 본 항목',
    zh: '最近查看',
    'zh-Hant': '最近查看',
    he: 'נצפה לאחרונה',
    ar: 'شوهد مؤخّرًا',
  },
  Done: {
    en: 'Done',
    de: 'Fertig',
    fr: 'Terminé',
    it: 'Fatto',
    es: 'Hecho',
    pl: 'Gotowe',
    pt: 'Concluído',
    tr: 'Tamam',
    ru: 'Готово',
    id: 'Selesai',
    ms: 'Selesai',
    th: 'เสร็จสิ้น',
    vi: 'Xong',
    ja: '完了',
    ko: '완료',
    zh: '完成',
    'zh-Hant': '完成',
    he: 'סיום',
    ar: 'تمّ',
  },
  // Explore Top100 screen
  Info: {
    en: 'Info',
    de: 'Info',
    fr: 'Infos',
    it: 'Info',
    es: 'Info',
    pl: 'Info',
    pt: 'Info',
    tr: 'Bilgi',
    ru: 'Инфо',
    id: 'Info',
    ms: 'Info',
    th: 'ข้อมูล',
    vi: 'Thông tin',
    ja: '情報',
    ko: '정보',
    zh: '信息',
    'zh-Hant': '資訊',
    he: 'מידע',
    ar: 'معلومات',
  },
  AsOf: {
    en: 'As of',
    de: 'Stand',
    fr: 'Au',
    it: 'Aggiornato al',
    es: 'A fecha de',
    pl: 'Na dzień',
    pt: 'Em',
    tr: 'Tarih',
    ru: 'По состоянию на',
    id: 'Per',
    ms: 'Setakat',
    th: 'อัปเดตเมื่อ',
    vi: 'Tính đến',
    ja: '時点',
    ko: '기준',
    zh: '截至',
    'zh-Hant': '截至',
    he: 'נכון ל-',
    ar: 'حتى',
  },
  All: {
    en: 'All',
    de: 'Alle',
    fr: 'Tout',
    it: 'Tutti',
    es: 'Todos',
    pl: 'Wszystko',
    pt: 'Todos',
    tr: 'Tümü',
    ru: 'Все',
    id: 'Semua',
    ms: 'Semua',
    th: 'ทั้งหมด',
    vi: 'Tất cả',
    ja: 'すべて',
    ko: '전체',
    zh: '全部',
    'zh-Hant': '全部',
    he: 'הכל',
    ar: 'الكل',
  },
  Domestic: {
    en: 'Domestic',
    de: 'Inland',
    fr: 'National',
    it: 'Domestico',
    es: 'Doméstico',
    pl: 'Krajowe',
    pt: 'Doméstico',
    tr: 'Yurtiçi',
    ru: 'Внутренний',
    id: 'Domestik',
    ms: 'Domestik',
    th: 'ในประเทศ',
    vi: 'Trong nước',
    ja: '国内',
    ko: '국내',
    zh: '国内',
    'zh-Hant': '國內',
    he: 'מקומי',
    ar: 'محلي',
  },
  Overseas: {
    en: 'Overseas',
    de: 'Ausland',
    fr: 'International',
    it: 'Estero',
    es: 'Extranjero',
    pl: 'Zagraniczne',
    pt: 'Internacional',
    tr: 'Yurtdışı',
    ru: 'Зарубежный',
    id: 'Luar negeri',
    ms: 'Luar negara',
    th: 'ต่างประเทศ',
    vi: 'Nước ngoài',
    ja: '海外',
    ko: '해외',
    zh: '海外',
    'zh-Hant': '海外',
    he: 'חו"ל',
    ar: 'دولي',
  },
  Realtime: {
    en: 'Realtime',
    de: 'Echtzeit',
    fr: 'Temps réel',
    it: 'Tempo reale',
    es: 'Tiempo real',
    pl: 'Na żywo',
    pt: 'Tempo real',
    tr: 'Canlı',
    ru: 'В реальном времени',
    id: 'Real-time',
    ms: 'Masa nyata',
    th: 'เรียลไทม์',
    vi: 'Thời gian thực',
    ja: 'リアルタイム',
    ko: '실시간',
    zh: '实时',
    'zh-Hant': '即時',
    he: 'זמן אמת',
    ar: 'لحظي',
  },
  OneDay: {
    en: '1 Day',
    de: '1 Tag',
    fr: '1 jour',
    it: '1 giorno',
    es: '1 día',
    pl: '1 dzień',
    pt: '1 dia',
    tr: '1 gün',
    ru: '1 день',
    id: '1 hari',
    ms: '1 hari',
    th: '1 วัน',
    vi: '1 ngày',
    ja: '1日',
    ko: '1일',
    zh: '1天',
    'zh-Hant': '1天',
    he: 'יום 1',
    ar: 'يوم واحد',
  },
  OneWeek: {
    en: '1 Week',
    de: '1 Woche',
    fr: '1 semaine',
    it: '1 settimana',
    es: '1 semana',
    pl: '1 tydzień',
    pt: '1 semana',
    tr: '1 hafta',
    ru: '1 неделя',
    id: '1 minggu',
    ms: '1 minggu',
    th: '1 สัปดาห์',
    vi: '1 tuần',
    ja: '1週',
    ko: '1주',
    zh: '1周',
    'zh-Hant': '1週',
    he: 'שבוע 1',
    ar: 'أسبوع واحد',
  },
  OneMonth: {
    en: '1 Month',
    de: '1 Monat',
    fr: '1 mois',
    it: '1 mese',
    es: '1 mes',
    pl: '1 miesiąc',
    pt: '1 mês',
    tr: '1 ay',
    ru: '1 месяц',
    id: '1 bulan',
    ms: '1 bulan',
    th: '1 เดือน',
    vi: '1 tháng',
    ja: '1ヶ月',
    ko: '1개월',
    zh: '1个月',
    'zh-Hant': '1個月',
    he: 'חודש 1',
    ar: 'شهر واحد',
  },
  ThreeMonths: {
    en: '3 Months',
    de: '3 Monate',
    fr: '3 mois',
    it: '3 mesi',
    es: '3 meses',
    pl: '3 miesiące',
    pt: '3 meses',
    tr: '3 ay',
    ru: '3 месяца',
    id: '3 bulan',
    ms: '3 bulan',
    th: '3 เดือน',
    vi: '3 tháng',
    ja: '3ヶ月',
    ko: '3개월',
    zh: '3个月',
    'zh-Hant': '3個月',
    he: '3 חודשים',
    ar: 'ثلاثة أشهر',
  },
  SixMonths: {
    en: '6 Months',
    de: '6 Monate',
    fr: '6 mois',
    it: '6 mesi',
    es: '6 meses',
    pl: '6 miesięcy',
    pt: '6 meses',
    tr: '6 ay',
    ru: '6 месяцев',
    id: '6 bulan',
    ms: '6 bulan',
    th: '6 เดือน',
    vi: '6 tháng',
    ja: '6ヶ月',
    ko: '6개월',
    zh: '6个月',
    'zh-Hant': '6個月',
    he: '6 חודשים',
    ar: 'ستة أشهر',
  },
  RealTimeTop10: {
    en: 'RealTime Top 10',
    de: 'Realtime Top 10',
    fr: 'Top 10 en temps réel',
    it: 'Top 10 tempo reale',
    es: 'Top 10 en tiempo real',
    pl: 'Top 10 na żywo',
    pt: 'Top 10 em tempo real',
    tr: 'Canlı Top 10',
    ru: 'Топ-10 в реальном времени',
    id: 'Top 10 real-time',
    ms: 'Top 10 masa nyata',
    th: 'ท็อป 10 แบบเรียลไทม์',
    vi: 'Top 10 thời gian thực',
    ja: 'リアルタイムTop 10',
    ko: '실시간 Top 10',
    zh: '实时前十',
    'zh-Hant': '即時前十',
    he: 'טופ 10 בזמן אמת',
    ar: 'أعلى 10 لحظيًا',
  },
  TradingVolume: {
    en: 'Volume',
    de: 'Volumen',
    fr: 'Volume',
    it: 'Volume',
    es: 'Volumen',
    pl: 'Wolumen',
    pt: 'Volume',
    tr: 'Hacim',
    ru: 'Объём',
    id: 'Volume',
    ms: 'Volum',
    th: 'ปริมาณ',
    vi: 'Khối lượng',
    ja: '出来高',
    ko: '거래량',
    zh: '成交量',
    'zh-Hant': '成交量',
    he: 'נפח',
    ar: 'حجم التداول',
  },
  TradingValue: {
    en: 'Trading value',
    de: 'Handelswert',
    fr: 'Valeur négociée',
    it: 'Valore scambiato',
    es: 'Valor negociado',
    pl: 'Wartość obrotu',
    pt: 'Valor negociado',
    tr: 'İşlem değeri',
    ru: 'Объём торгов в деньгах',
    id: 'Nilai transaksi',
    ms: 'Nilai dagangan',
    th: 'มูลค่าการซื้อขาย',
    vi: 'Giá trị giao dịch',
    ja: '売買代金',
    ko: '거래대금',
    zh: '成交额',
    'zh-Hant': '成交額',
    he: 'שווי מסחר',
    ar: 'قيمة التداول',
  },
  PopularLower: {
    en: 'Popular',
    de: 'Beliebt',
    fr: 'Populaire',
    it: 'Popolare',
    es: 'Popular',
    pl: 'Popularne',
    pt: 'Popular',
    tr: 'Popüler',
    ru: 'Популярное',
    id: 'Populer',
    ms: 'Popular',
    th: 'ยอดนิยม',
    vi: 'Phổ biến',
    ja: '人気',
    ko: '인기',
    zh: '热门',
    'zh-Hant': '熱門',
    he: 'פופולרי',
    ar: 'شائع',
  },
  Rising: {
    en: 'Rising',
    de: 'Steigend',
    fr: 'En hausse',
    it: 'In rialzo',
    es: 'Subiendo',
    pl: 'Wzrosty',
    pt: 'Em alta',
    tr: 'Yükselen',
    ru: 'Растёт',
    id: 'Naik',
    ms: 'Meningkat',
    th: 'กำลังขึ้น',
    vi: 'Tăng',
    ja: '上昇',
    ko: '상승',
    zh: '上涨',
    'zh-Hant': '上漲',
    he: 'עולה',
    ar: 'صاعد',
  },
  Falling: {
    en: 'Falling',
    de: 'Fallend',
    fr: 'En baisse',
    it: 'In calo',
    es: 'Bajando',
    pl: 'Spadki',
    pt: 'Em queda',
    tr: 'Düşen',
    ru: 'Падает',
    id: 'Turun',
    ms: 'Menurun',
    th: 'กำลังลง',
    vi: 'Giảm',
    ja: '下落',
    ko: '하락',
    zh: '下跌',
    'zh-Hant': '下跌',
    he: 'יורד',
    ar: 'هابط',
  },
  Top100ByTradingVolume: {
    en: 'Top 100 by Trading Volume',
    de: 'Top 100 nach Handelsvolumen',
    fr: 'Top 100 par volume échangé',
    it: 'Top 100 per volume di scambio',
    es: 'Top 100 por volumen',
    pl: 'Top 100 według wolumenu',
    pt: 'Top 100 por volume negociado',
    tr: 'Hacme göre ilk 100',
    ru: 'Топ-100 по объёму торгов',
    id: 'Top 100 menurut volume perdagangan',
    ms: '100 teratas mengikut volum dagangan',
    th: 'ท็อป 100 ตามปริมาณซื้อขาย',
    vi: 'Top 100 theo khối lượng giao dịch',
    ja: '出来高トップ100',
    ko: '거래량 상위 100',
    zh: '成交量前100',
    'zh-Hant': '成交量前100',
    he: '100 המובילות בנפח מסחר',
    ar: 'أفضل 100 حسب حجم التداول',
  },
  Top100ByTradingValue: {
    en: 'Top 100 by Trading Value',
    de: 'Top 100 nach Handelswert',
    fr: 'Top 100 par valeur échangée',
    it: 'Top 100 per valore di scambio',
    es: 'Top 100 por valor',
    pl: 'Top 100 według wartości obrotu',
    pt: 'Top 100 por valor negociado',
    tr: 'İşlem değerine göre ilk 100',
    ru: 'Топ-100 по обороту',
    id: 'Top 100 menurut nilai perdagangan',
    ms: '100 teratas mengikut nilai dagangan',
    th: 'ท็อป 100 ตามมูลค่าซื้อขาย',
    vi: 'Top 100 theo giá trị giao dịch',
    ja: '売買代金トップ100',
    ko: '거래대금 상위 100',
    zh: '成交额前100',
    'zh-Hant': '成交額前100',
    he: '100 המובילות בערך מסחר',
    ar: 'أفضل 100 حسب قيمة التداول',
  },
  Top100ByPopular: {
    en: 'Top 100 by Popular',
    de: 'Top 100 nach Beliebtheit',
    fr: 'Top 100 par popularité',
    it: 'Top 100 per popolarità',
    es: 'Top 100 por popularidad',
    pl: 'Top 100 według popularności',
    pt: 'Top 100 por popularidade',
    tr: 'Popülerliğe göre ilk 100',
    ru: 'Топ-100 по популярности',
    id: 'Top 100 menurut popularitas',
    ms: '100 teratas mengikut populariti',
    th: 'ท็อป 100 ตามความนิยม',
    vi: 'Top 100 theo mức phổ biến',
    ja: '人気トップ100',
    ko: '인기 상위 100',
    zh: '人气前100',
    'zh-Hant': '人氣前100',
    he: '100 המובילות בפופולריות',
    ar: 'أفضل 100 حسب الشعبية',
  },
  Top100RapidIncreasing: {
    en: 'Top 100 Rapid Increasing',
    de: 'Top 100 schnell steigend',
    fr: 'Top 100 hausses rapides',
    it: 'Top 100 in rapido aumento',
    es: 'Top 100 aumento rápido',
    pl: 'Top 100 najszybciej rosnących',
    pt: 'Top 100 em rápida alta',
    tr: 'Hızla yükselen ilk 100',
    ru: 'Топ-100 быстрый рост',
    id: 'Top 100 naik cepat',
    ms: 'Top 100 meningkat pantas',
    th: 'ท็อป 100 เพิ่มขึ้นเร็ว',
    vi: 'Top 100 tăng nhanh',
    ja: '急騰トップ100',
    ko: '급등 상위 100',
    zh: '快速上涨前100',
    'zh-Hant': '快速上漲前100',
    he: '100 המובילות בעלייה מהירה',
    ar: 'أفضل 100 ارتفاعًا سريعًا',
  },
  Top100FallingDown: {
    en: 'Top 100 Falling Down',
    de: 'Top 100 stark fallend',
    fr: 'Top 100 fortes baisses',
    it: 'Top 100 in rapido calo',
    es: 'Top 100 caída',
    pl: 'Top 100 najszybciej spadających',
    pt: 'Top 100 em forte queda',
    tr: 'Hızla düşen ilk 100',
    ru: 'Топ-100 сильное падение',
    id: 'Top 100 turun tajam',
    ms: 'Top 100 jatuh mendadak',
    th: 'ท็อป 100 ลดลงเร็ว',
    vi: 'Top 100 giảm mạnh',
    ja: '急落トップ100',
    ko: '급락 상위 100',
    zh: '下跌前100',
    'zh-Hant': '下跌前100',
    he: '100 המובילות בירידה חדה',
    ar: 'أفضل 100 انخفاضًا حادًا',
  },
  // Markets
  Markets: {
    en: 'Markets',
    de: 'Märkte',
    fr: 'Marchés',
    it: 'Mercati',
    es: 'Mercados',
    pl: 'Rynki',
    pt: 'Mercados',
    tr: 'Piyasalar',
    ru: 'Рынки',
    id: 'Pasar',
    ms: 'Pasaran',
    th: 'ตลาด',
    vi: 'Thị trường',
    ja: 'マーケット',
    ko: '마켓',
    zh: '市场',
    'zh-Hant': '市場',
    he: 'שווקים',
    ar: 'الأسواق',
  },
  Indices: {
    en: 'Indices',
    de: 'Indizes',
    fr: 'Indices',
    it: 'Indici',
    es: 'Índices',
    pl: 'Indeksy',
    pt: 'Índices',
    tr: 'Endeksler',
    ru: 'Индексы',
    id: 'Indeks',
    ms: 'Indeks',
    th: 'ดัชนี',
    vi: 'Chỉ số',
    ja: '指数',
    ko: '지수',
    zh: '指数',
    'zh-Hant': '指數',
    he: 'מדדים',
    ar: 'المؤشرات',
  },
  Commodities: {
    en: 'Commodities',
    de: 'Rohstoffe',
    fr: 'Matières premières',
    it: 'Materie prime',
    es: 'Materias primas',
    pl: 'Surowce',
    pt: 'Commodities',
    tr: 'Emtialar',
    ru: 'Товары',
    id: 'Komoditas',
    ms: 'Komoditi',
    th: 'สินค้าโภคภัณฑ์',
    vi: 'Hàng hóa',
    ja: '商品',
    ko: '원자재',
    zh: '商品',
    'zh-Hant': '商品',
    he: 'סחורות',
    ar: 'السلع',
  },
  Futures: {
    en: 'Futures',
    de: 'Futures',
    fr: 'Futures',
    it: 'Futures',
    es: 'Futuros',
    pl: 'Kontrakty terminowe',
    pt: 'Futuros',
    tr: 'Vadeli işlemler',
    ru: 'Фьючерсы',
    id: 'Futures',
    ms: 'Niaga hadapan',
    th: 'สัญญาฟิวเจอร์ส',
    vi: 'Hợp đồng tương lai',
    ja: '先物',
    ko: '선물',
    zh: '期货',
    'zh-Hant': '期貨',
    he: 'חוזים עתידיים',
    ar: 'العقود الآجلة',
  },
  Currencies: {
    en: 'Currencies',
    de: 'Währungen',
    fr: 'Devises',
    it: 'Valute',
    es: 'Divisas',
    pl: 'Waluty',
    pt: 'Moedas',
    tr: 'Kurlar',
    ru: 'Валюты',
    id: 'Mata uang',
    ms: 'Mata wang',
    th: 'สกุลเงิน',
    vi: 'Tiền tệ',
    ja: '為替',
    ko: '환율',
    zh: '货币',
    'zh-Hant': '貨幣',
    he: 'מטבעות',
    ar: 'العملات',
  },
  // Home (AI Highlights, segments, stats)
  AIHighlights: {
    en: 'AI Highlights',
    de: 'KI-Highlights',
    fr: 'Temps forts IA',
    it: 'In evidenza IA',
    es: 'Destacados de IA',
    pl: 'Najważniejsze AI',
    pt: 'Destaques de IA',
    tr: 'Yapay Zeka Öne Çıkanlar',
    ru: 'Главное от ИИ',
    id: 'Sorotan AI',
    ms: 'Sorotan AI',
    th: 'ไฮไลต์จาก AI',
    vi: 'Điểm nhấn AI',
    ja: 'AI ハイライト',
    ko: 'AI 하이라이트',
    zh: 'AI 精选',
    'zh-Hant': 'AI 精選',
    he: 'נקודות שיא של בינה מלאכותית',
    ar: 'أبرز ما لدى الذكاء الاصطناعي',
  },
  AISubtitle: {
    en: 'Hype-aware. Signal-first.',
    de: 'Hype-bewusst. Signal zuerst.',
    fr: 'Conscient du buzz. Priorité au signal.',
    it: 'Consapevole del clamore. Prima il segnale.',
    es: 'Consciente del hype. Señal primero.',
    pl: 'Świadomość hype’u. Najpierw sygnał.',
    pt: 'Ciente do hype. Sinal em primeiro lugar.',
    tr: 'Hype farkında. Önce sinyal.',
    ru: 'Чувствует хайп. Сначала сигнал.',
    id: 'Sadar hype. Utamakan sinyal.',
    ms: 'Sedari hype. Isyarat diutamakan.',
    th: 'รู้เท่าทันกระแส เน้นสัญญาณก่อน',
    vi: 'Nhận biết hype. Ưu tiên tín hiệu.',
    ja: 'ハイプ認識。シグナル優先。',
    ko: '떡상 감지. 신호에 집중.',
    zh: '感知热度，信号优先。',
    'zh-Hant': '洞悉熱度，信號為先。',
    he: 'מודע להייפ. הסיגנל קובע.',
    ar: 'واعي بالضجة. الإشارة أولًا.',
  },
  FOMO: {
    en: 'FOMO',
    de: 'FOMO',
    fr: 'FOMO',
    it: 'FOMO',
    es: 'FOMO',
    pl: 'FOMO',
    pt: 'FOMO',
    tr: 'FOMO',
    ru: 'FOMO',
    id: 'FOMO',
    ms: 'FOMO',
    th: 'FOMO',
    vi: 'FOMO',
    ja: 'FOMO',
    ko: 'FOMO',
    zh: 'FOMO',
    'zh-Hant': 'FOMO',
    he: 'FOMO',
    ar: 'FOMO',
  },
  Balanced: {
    en: 'Balanced',
    de: 'Ausgewogen',
    fr: 'Équilibré',
    it: 'Bilanciato',
    es: 'Equilibrado',
    pl: 'Zrównoważony',
    pt: 'Equilibrado',
    tr: 'Dengeli',
    ru: 'Сбалансировано',
    id: 'Seimbang',
    ms: 'Seimbang',
    th: 'สมดุล',
    vi: 'Cân bằng',
    ja: 'バランス',
    ko: '밸런스',
    zh: '均衡',
    'zh-Hant': '均衡',
    he: 'מאוזן',
    ar: 'متوازن',
  },
  Yoink: {
    en: 'yoink!',
    de: 'yoink!',
    fr: 'yoink!',
    it: 'yoink!',
    es: 'yoink!',
    pl: 'yoink!',
    pt: 'yoink!',
    tr: 'yoink!',
    ru: 'yoink!',
    id: 'yoink!',
    ms: 'yoink!',
    th: 'yoink!',
    vi: 'yoink!',
    ja: 'yoink!',
    ko: 'yoink!',
    zh: 'yoink!',
    'zh-Hant': 'yoink!',
    he: 'yoink!',
    ar: 'yoink!',
  },
  Hottest: {
    en: 'Hottest',
    de: 'Am heißesten',
    fr: 'Le plus chaud',
    it: 'Più bollente',
    es: 'Más caliente',
    pl: 'Najgorętsze',
    pt: 'Mais quente',
    tr: 'En sıcak',
    ru: 'Самое горячее',
    id: 'Paling panas',
    ms: 'Paling hangat',
    th: 'ฮอตที่สุด',
    vi: 'Nóng nhất',
    ja: '最熱',
    ko: '가장 핫한종목',
    zh: '最热',
    'zh-Hant': '最熱',
    he: 'החם ביותר',
    ar: 'الأكثر سخونة',
  },
  Risk: {
    en: 'Risk',
    de: 'Risiko',
    fr: 'Risque',
    it: 'Rischio',
    es: 'Riesgo',
    pl: 'Ryzyko',
    pt: 'Risco',
    tr: 'Risk',
    ru: 'Риск',
    id: 'Risiko',
    ms: 'Risiko',
    th: 'ความเสี่ยง',
    vi: 'Rủi ro',
    ja: 'リスク',
    ko: '위험도',
    zh: '风险',
    'zh-Hant': '風險',
    he: 'סיכון',
    ar: 'المخاطر',
  },
  None: {
    en: 'None',
    de: 'Keine',
    fr: 'Aucun',
    it: 'Nessuno',
    es: 'Ninguno',
    pl: 'Brak',
    pt: 'Nenhum',
    tr: 'Yok',
    ru: 'Нет',
    id: 'Tidak ada',
    ms: 'Tiada',
    th: 'ไม่มี',
    vi: 'Không',
    ja: 'なし',
    ko: '없음',
    zh: '无',
    'zh-Hant': '無',
    he: 'אין',
    ar: 'بلا',
  },
  TopPick: {
    en: 'Top Pick',
    de: 'Top-Tipp',
    fr: 'Choix du moment',
    it: 'Scelta top',
    es: 'Mejor elección',
    pl: 'Top wybór',
    pt: 'Escolha top',
    tr: 'Öne çıkan',
    ru: 'Топ выбор',
    id: 'Pilihan utama',
    ms: 'Pilihan teratas',
    th: 'ตัวเลือกเด่น',
    vi: 'Lựa chọn hàng đầu',
    ja: 'トップピック',
    ko: '추천',
    zh: '首选',
    'zh-Hant': '首選',
    he: 'בחירה מובילה',
    ar: 'الاختيار الأفضل',
  },
  LOW: {
    en: 'LOW',
    de: 'NIEDRIG',
    fr: 'BAS',
    it: 'BASSO',
    es: 'BAJO',
    pl: 'NISKI',
    pt: 'BAIXO',
    tr: 'DÜŞÜK',
    ru: 'НИЗКИЙ',
    id: 'RENDAH',
    ms: 'RENDAH',
    th: 'ต่ำ',
    vi: 'THẤP',
    ja: '低',
    ko: '낮음',
    zh: '低',
    'zh-Hant': '低',
    he: 'נמוך',
    ar: 'منخفض',
  },
  HIGH: {
    en: 'HIGH',
    de: 'HOCH',
    fr: 'ÉLEVÉ',
    it: 'ALTO',
    es: 'ALTO',
    pl: 'WYSOKI',
    pt: 'ALTO',
    tr: 'YÜKSEK',
    ru: 'ВЫСОКИЙ',
    id: 'TINGGI',
    ms: 'TINGGI',
    th: 'สูง',
    vi: 'CAO',
    ja: '高',
    ko: '높음',
    zh: '高',
    'zh-Hant': '高',
    he: 'גבוה',
    ar: 'مرتفع',
  },
  Stable: {
    en: 'Stable',
    de: 'Stabil',
    fr: 'Stable',
    it: 'Stabile',
    es: 'Estable',
    pl: 'Stabilny',
    pt: 'Estável',
    tr: 'Stabil',
    ru: 'Стабильно',
    id: 'Stabil',
    ms: 'Stabil',
    th: 'เสถียร',
    vi: 'Ổn định',
    ja: '安定',
    ko: '안정적',
    zh: '稳定',
    'zh-Hant': '穩定',
    he: 'יציב',
    ar: 'مستقر',
  },
  Picks: {
    en: 'picks',
    de: 'auswahlen',
    fr: 'sélections',
    it: 'scelte',
    es: 'selecciones',
    pl: 'wybory',
    pt: 'escolhas',
    tr: 'seçimler',
    ru: 'выборы',
    id: 'pilihan',
    ms: 'pilihan',
    th: 'ตัวเลือก',
    vi: 'lựa chọn',
    ja: '銘柄',
    ko: '종목',
    zh: '个标的',
    'zh-Hant': '標的',
    he: 'בחירות',
    ar: 'اختيارات',
  },
  Moonshot: {
    en: 'Moonshot',
    de: 'Mondflug',
    fr: 'Vers la lune',
    it: 'Verso la luna',
    es: 'Rumbo a la luna',
    pl: 'Lot na Księżyc',
    pt: 'Rumo à lua',
    tr: 'Aya yolculuk',
    ru: 'Полет на Луну',
    id: 'Menuju bulan',
    ms: 'Menuju bulan',
    th: 'พุ่งสู่ดวงจันทร์',
    vi: 'Bay lên Mặt Trăng',
    ja: '月への飛翔',
    ko: '달로 간다',
    zh: '飞向月球',
    'zh-Hant': '飛向月球',
    he: 'אל הירח',
    ar: 'إلى القمر',
  },
  EXTREME: {
    en: 'EXTREME',
    de: 'EXTREM',
    fr: 'EXTRÊME',
    it: 'ESTREMO',
    es: 'EXTREMO',
    pl: 'EKSTREMALNE',
    pt: 'EXTREMO',
    tr: 'AŞIRI',
    ru: 'ЭКСТРИМ',
    id: 'EKSTREM',
    ms: 'EKSTREM',
    th: 'สุดขั้ว',
    vi: 'CỰC ĐỘ',
    ja: '極端',
    ko: '초위험',
    zh: '极端',
    'zh-Hant': '極端',
    he: 'קיצוני',
    ar: 'شديد',
  },
  Crashing: {
    en: 'Crashing',
    de: 'Absturz',
    fr: 'Effondrement',
    it: 'Crollo',
    es: 'Desplome',
    pl: 'Krach',
    pt: 'Queda acentuada',
    tr: 'Çöken',
    ru: 'Падает',
    id: 'Anjlok',
    ms: 'Menjunam',
    th: 'ร่วงหนัก',
    vi: 'Rơi mạnh',
    ja: '暴落',
    ko: '폭락주',
    zh: '暴跌',
    'zh-Hant': '暴跌',
    he: 'מתרסק',
    ar: 'ينهار',
  },
  Unlocked24h: {
    en: 'Unlocked — 24h access',
    de: 'Freigeschaltet — 24h Zugriff',
    fr: 'Débloqué — accès 24h',
    it: 'Sbloccato — accesso 24h',
    es: 'Desbloqueado — acceso 24h',
    pl: 'Odblokowano — dostęp 24h',
    pt: 'Desbloqueado — acesso 24h',
    tr: 'Kilidi açıldı — 24 saat erişim',
    ru: 'Разблокировано — доступ 24 часа',
    id: 'Terbuka — akses 24 jam',
    ms: 'Dibuka — akses 24 jam',
    th: 'ปลดล็อก — ใช้งานได้ 24 ชม.',
    vi: 'Đã mở khóa — truy cập 24h',
    ja: 'アンロック — 24時間アクセス',
    ko: '잠금 해제 — 24시간 접근',
    zh: '已解锁 — 24小时访问',
    'zh-Hant': '已解鎖 — 24小時存取',
    he: 'נפתח — גישה 24 שעות',
    ar: 'مفتوح — وصول 24 ساعة',
  },
  // Activity sections
  SavedEmptyDesc: {
    en: 'Your saved items will appear here.',
    de: 'Deine gespeicherten Elemente werden hier angezeigt.',
    fr: 'Vos éléments enregistrés apparaîtront ici.',
    it: 'I tuoi elementi salvati appariranno qui.',
    es: 'Tus elementos guardados aparecerán aquí.',
    pl: 'Twoje zapisane elementy pojawią się tutaj.',
    pt: 'Seus itens salvos aparecerão aqui.',
    tr: 'Kaydettiğin öğeler burada görünecek.',
    ru: 'Сохранённые элементы появятся здесь.',
    id: 'Item tersimpan Anda akan muncul di sini.',
    ms: 'Item yang anda simpan akan muncul di sini.',
    th: 'รายการที่บันทึกของคุณจะแสดงที่นี่',
    vi: 'Mục đã lưu của bạn sẽ xuất hiện tại đây.',
    ja: '保存した項目がここに表示されます。',
    ko: '저장한 항목이 여기에 표시됩니다.',
    zh: '你保存的项目会显示在这里。',
    'zh-Hant': '你儲存的項目會顯示在這裡。',
    he: 'הפריטים ששמרת יופיעו כאן.',
    ar: 'العناصر المحفوظة الخاصة بك ستظهر هنا.',
  },
  YourActivityIntro: {
    en: 'One place to manage your activity',
    de: 'Ein Ort, um deine Aktivität zu verwalten.',
    fr: 'Un seul endroit pour gérer votre activité.',
    it: 'Un unico luogo per gestire la tua attività.',
    es: 'Un lugar para gestionar tu actividad.',
    pl: 'Jedno miejsce do zarządzania swoją aktywnością.',
    pt: 'Um só lugar para gerenciar sua atividade.',
    tr: 'Aktiviteni yönetebileceğin tek yer.',
    ru: 'Одно место для управления вашей активностью.',
    id: 'Satu tempat untuk mengelola aktivitas Anda.',
    ms: 'Satu tempat untuk mengurus aktiviti anda.',
    th: 'จุดเดียวสำหรับจัดการกิจกรรมของคุณ',
    vi: 'Một nơi để quản lý hoạt động của bạn.',
    ja: 'アクティビティを1か所で管理。',
    ko: '내 활동을 한곳에서 관리하세요.',
    zh: '在一个地方管理你的活动',
    'zh-Hant': '在一個地方管理你的活動',
    he: 'מקום אחד לניהול הפעילות שלך.',
    ar: 'مكان واحد لإدارة نشاطك.',
  },
  MenuSubtitle: { en: 'Account, app status, settings, and support.', pl: 'Konto, status aplikacji, ustawienia i wsparcie.' },
  SignInSyncLater: { en: 'Sign in to sync settings and saved items later', pl: 'Zaloguj się, aby później synchronizować ustawienia i zapisane elementy' },
  SignedIn: { en: 'Signed in', pl: 'Zalogowano' },
  Guest: { en: 'Guest', pl: 'Gość' },
  SignInRegister: { en: 'Sign in / Register', pl: 'Zaloguj się / Zarejestruj' },
  Logout: { en: 'Logout', pl: 'Wyloguj' },
  SavedSyncLabel: { en: 'Saved sync', pl: 'Synchronizacja zapisanych' },
  SavedLocalLabel: { en: 'Saved local', pl: 'Zapisane lokalnie' },
  NeedsRetry: { en: 'needs retry', pl: 'wymaga ponowienia' },
  AccountWatchlist: { en: 'account watchlist', pl: 'lista konta' },
  GuestDeviceList: { en: 'guest device list', pl: 'lista urządzenia gościa' },
  MarketFeed: { en: 'Market feed', pl: 'Feed rynku' },
  TrackedCoinsCount: { en: 'tracked coins', pl: 'śledzone monety' },
  StatusLabel: { en: 'Status', pl: 'Status' },
  LiveStatus: { en: 'Live', pl: 'Na żywo' },
  OfflineStatus: { en: 'Offline', pl: 'Offline' },
  WaitingForIngest: { en: 'Waiting for ingest', pl: 'Oczekiwanie na ingest' },
  NoTimestamp: { en: 'No timestamp', pl: 'Brak znacznika czasu' },
  SyncLabel: { en: 'Sync', pl: 'Synchronizacja' },
  AccountMode: { en: 'Account', pl: 'Konto' },
  LocalMode: { en: 'Local', pl: 'Lokalnie' },
  AuthSessionReady: { en: 'Auth session ready', pl: 'Sesja uwierzytelniania gotowa' },
  DeviceOnlyMode: { en: 'Device-only mode', pl: 'Tryb tylko na urządzeniu' },
  ProductStatus: { en: 'Product status', pl: 'Status produktu' },
  AuthFlowLive: { en: 'Auth flow is live', pl: 'Logowanie działa na żywo' },
  MarketFeedPowered: { en: 'Market feed is powered by Supabase', pl: 'Feed rynku działa na Supabase' },
  SavedCoinsLocalOnly: { en: 'Saved coins are local-only for now', pl: 'Zapisane monety są na razie tylko lokalne' },
  SavedCoinsGuestStatus: { en: 'Saved coins stay on this device until you sign in', pl: 'Zapisane monety pozostają na tym urządzeniu, dopóki się nie zalogujesz' },
  SavedCoinsAccountStatus: { en: 'Saved coins sync to your account watchlist in Supabase', pl: 'Zapisane monety synchronizują się z watchlistą konta w Supabase' },
  ScoutersPresetsLive: { en: 'Scouters use live presets; custom scanners come next', pl: 'Zwiadowcy używają presetów live; własne skanery pojawią się później' },
  ExploreTrack: { en: 'Explore & track', pl: 'Odkrywaj i śledź' },
  ExploreLiveMarketBoard: { en: 'Explore live market board', pl: 'Odkrywaj tablicę rynku na żywo' },
  ExploreLiveDataFirstTitle: { en: 'Explore is live-data first now', pl: 'Odkrywaj działa teraz przede wszystkim na danych live' },
  ExploreSavedGuestBody: { en: 'Tap a coin row to open details. Bookmark icons save coins on this device until you sign in; shared watchlists and alerts are still being built.', pl: 'Dotknij wiersza monety, aby otworzyć szczegóły. Ikony zakładki zapisują monety na tym urządzeniu, dopóki się nie zalogujesz; współdzielone watchlisty i alerty są nadal w budowie.' },
  ExploreSavedAccountBody: { en: 'Tap a coin row to open details. Bookmark icons sync coins to your account watchlist; shared watchlists and alerts are still being built.', pl: 'Dotknij wiersza monety, aby otworzyć szczegóły. Ikony zakładki synchronizują monety z watchlistą Twojego konta; współdzielone watchlisty i alerty są nadal w budowie.' },
  Top100Rankings: { en: 'Top 100 rankings', pl: 'Ranking Top 100' },
  Admin: { en: 'Admin', pl: 'Admin' },
  AdminPanel: { en: 'Admin panel', pl: 'Panel admina' },
  AppTagline: { en: 'Crypto intelligence. Signal first.', pl: 'Inteligencja krypto. Najpierw sygnał.' },
  SavedCoinsTitle: { en: 'Saved coins', pl: 'Zapisane monety' },
  SavedCoinsSubtitleDevice: { en: 'Your watchlist is stored on this device for now.', pl: 'Twoja lista obserwowanych jest na razie zapisana na tym urządzeniu.' },
  SavedCoinsSubtitleAccount: { en: 'Saved coins are synced to your account and cached on this device.', pl: 'Zapisane monety są synchronizowane z kontem i buforowane na tym urządzeniu.' },
  SavedCoinsSubtitleRetry: { en: 'Saved coins are cached locally and will retry syncing to your account.', pl: 'Zapisane monety są zapisane lokalnie i spróbują ponownie zsynchronizować się z kontem.' },
  TrackedNow: { en: 'Tracked now', pl: 'Śledzone teraz' },
  NextStep: { en: 'Next step', pl: 'Następny krok' },
  TapAnyCoinForDetails: { en: 'Tap any coin for details', pl: 'Dotknij monety, aby zobaczyć szczegóły' },
  NoSavedCoinsYet: { en: 'No saved coins yet', pl: 'Brak zapisanych monet' },
  SaveCoinsFromExplore: { en: 'Save coins from Explore or the coin detail screen and they will appear here.', pl: 'Zapisz monety w Odkrywaj lub na ekranie szczegółów monety, a pojawią się tutaj.' },
  GoToExplore: { en: 'Go to Explore', pl: 'Przejdź do Odkrywaj' },
  FailedToLoadLivePrices: { en: 'Failed to load live prices', pl: 'Nie udało się załadować cen na żywo' },
  SavedSymbolsReady: { en: 'Saved symbols are ready', pl: 'Zapisane symbole są gotowe' },
  SavedSymbolsReadyBody: { en: 'Live market rows will appear here after the next ingest run populates Supabase data.', pl: 'Wiersze rynku na żywo pojawią się tutaj po następnym przebiegu ingestu, gdy dane trafią do Supabase.' },
  LiveMarketBoardTitle: { en: 'Live market board', pl: 'Tablica rynku na żywo' },
  TapAnyCoinDetails: { en: 'Tap any coin for details.', pl: 'Dotknij dowolnej monety, aby zobaczyć szczegóły.' },
  LiveBadge: { en: 'LIVE', pl: 'LIVE' },
  VolProxy: { en: 'Vol proxy', pl: 'Proxy wolumenu' },
  MarketRankLabel: { en: 'Market rank', pl: 'Pozycja rynkowa' },
  Vol24Label: { en: '24H vol', pl: 'Wol. 24h' },
  LivePresetsTitle: { en: 'Live signal presets', pl: 'Presety sygnałów live' },
  LivePresetsBody: { en: 'These presets use current Supabase market data. Custom saved scanners can come later if we add dedicated backend support.', pl: 'Te presety używają bieżących danych rynkowych z Supabase. Własne zapisane skanery mogą pojawić się później, jeśli dodamy dedykowane wsparcie backendowe.' },
  LastMarketUpdate: { en: 'Last market update', pl: 'Ostatnia aktualizacja rynku' },
  LoadingLiveScouters: { en: 'Loading live scouters…', pl: 'Ładowanie zwiadowców live…' },
  CouldNotLoadScouters: { en: 'Could not load scouters', pl: 'Nie udało się załadować zwiadowców' },
  NoLiveMatchesYet: { en: 'No live matches yet. Pull to refresh after ingest runs.', pl: 'Brak dopasowań live. Odśwież po zakończeniu ingestu.' },
  RefreshLiveScanners: { en: 'Refresh live signals', pl: 'Odśwież sygnały live' },
  ViewMatches: { en: 'View matches', pl: 'Zobacz dopasowania' },
  LiveMatchesFor: { en: 'Live matches · {name}', pl: 'Dopasowania live · {name}' },
  NoScouterMatchesBody: { en: 'No matches currently satisfy this preset. Pull to refresh after the next market ingest run.', pl: 'Obecnie żadne dopasowania nie spełniają tego presetu. Odśwież po następnym przebiegu ingestu rynku.' },
  SignalPresetsSection: { en: 'Live signal presets', pl: 'Presety sygnałów live' },
  SignalMatchesCount: { en: 'live matches', pl: 'dopasowania live' },
  ComingSoon: { en: 'Coming soon', pl: 'Wkrótce' },
  ComingSoonSignals: { en: 'Next signal ideas', pl: 'Następne pomysły na sygnały' },
  ComingSoonSignalsBody: { en: 'These presets need additional datasets before they can produce useful matches in the app.', pl: 'Te presety potrzebują dodatkowych zbiorów danych, zanim będą mogły dawać użyteczne dopasowania w aplikacji.' },
  RefreshData: { en: 'Refresh data', pl: 'Odśwież dane' },
  SignalUpdated: { en: 'Updated', pl: 'Zaktualizowano' },
  MatchesNow: { en: 'matches now', pl: 'dopasowania teraz' },
  RelativeJustNow: { en: 'just now', pl: 'przed chwilą' },
  RelativeMinutesAgo: { en: '{count}m ago', pl: '{count} min temu' },
  RelativeHoursAgo: { en: '{count}h ago', pl: '{count} godz. temu' },
  RelativeDaysAgo: { en: '{count}d ago', pl: '{count} dni temu' },
  PlaceholderWhatBelongsHere: { en: 'What belongs here', pl: 'Co tu trafi' },
  AuthModeSignIn: { en: 'Sign in', pl: 'Zaloguj się' },
  AuthModeCreateAccount: { en: 'Create account', pl: 'Utwórz konto' },
  AuthUseEmailPassword: { en: 'Use your email and password to access the app.', pl: 'Użyj e-maila i hasła, aby wejść do aplikacji.' },
  AuthCreateTesterAccount: { en: 'Create a tester/admin-ready account with a stronger password.', pl: 'Utwórz konto testera/admina z mocniejszym hasłem.' },
  AuthEmail: { en: 'Email', pl: 'E-mail' },
  AuthPassword: { en: 'Password', pl: 'Hasło' },
  AuthPasswordPlaceholder: { en: 'Your password', pl: 'Twoje hasło' },
  AuthForNewAccounts: { en: 'For new accounts', pl: 'Dla nowych kont' },
  AuthStartTyping: { en: 'Start typing', pl: 'Zacznij pisać' },
  AuthWeak: { en: 'Weak', pl: 'Słabe' },
  AuthGood: { en: 'Good', pl: 'Dobre' },
  AuthStrong: { en: 'Strong', pl: 'Mocne' },
  Auth12Chars: { en: '12+ characters', pl: '12+ znaków' },
  AuthUppercase: { en: 'Uppercase letter', pl: 'Wielka litera' },
  AuthLowercase: { en: 'Lowercase letter', pl: 'Mała litera' },
  AuthNumber: { en: 'Number', pl: 'Cyfra' },
  AuthConfirmPassword: { en: 'Confirm password', pl: 'Potwierdź hasło' },
  AuthConfirmPasswordPlaceholder: { en: 'Repeat password for new accounts', pl: 'Powtórz hasło dla nowego konta' },
  AuthPasswordsMatch: { en: 'Passwords match', pl: 'Hasła są zgodne' },
  AuthRepeatPasswordForCreation: { en: 'Repeat your password for account creation', pl: 'Powtórz hasło, aby utworzyć konto' },
  AuthForgotPassword: { en: 'Forgot password?', pl: 'Zapomniałeś hasła?' },
  AuthSendingResetEmail: { en: 'Sending reset email…', pl: 'Wysyłanie e-maila resetującego…' },
  AuthContinue: { en: 'Continue', pl: 'Kontynuuj' },
  AuthCreateAccountAction: { en: 'Create account', pl: 'Utwórz konto' },
  AuthCreateAccountInstead: { en: 'Create account instead', pl: 'Zamiast tego utwórz konto' },
  AuthBackToSignIn: { en: 'Back to sign in', pl: 'Wróć do logowania' },
  AuthEmailConfirmationNote: { en: 'If email confirmation is enabled, you’ll verify the account before signing in.', pl: 'Jeśli potwierdzenie e-maila jest włączone, zweryfikujesz konto przed zalogowaniem.' },
  AuthEnterEmailPassword: { en: 'Please enter email and password.', pl: 'Wpisz e-mail i hasło.' },
  AuthValidEmail: { en: 'Please enter a valid email address.', pl: 'Wpisz poprawny adres e-mail.' },
  AuthPasswordRulesError: { en: 'Use 12+ characters with uppercase, lowercase, and a number.', pl: 'Użyj co najmniej 12 znaków, wielkiej litery, małej litery i cyfry.' },
  AuthConfirmPasswordMissing: { en: 'Please confirm your password.', pl: 'Potwierdź hasło.' },
  AuthPasswordsMismatch: { en: 'Passwords do not match.', pl: 'Hasła nie są zgodne.' },
  AuthCreateRedirecting: { en: 'Account created. Redirecting…', pl: 'Konto utworzone. Przekierowywanie…' },
  AuthCheckEmail: { en: 'Account created. Check your email if confirmation is required, then sign in.', pl: 'Konto utworzone. Sprawdź e-mail, jeśli wymagane jest potwierdzenie, a potem się zaloguj.' },
  AuthGenericError: { en: 'Something went wrong. Please try again.', pl: 'Coś poszło nie tak. Spróbuj ponownie.' },
  AuthEnterEmailFirst: { en: 'Enter your email address first.', pl: 'Najpierw wpisz adres e-mail.' },
  AuthResetPasswordSent: { en: 'Password reset email sent. Open the link on this device/browser to continue.', pl: 'E-mail resetujący hasło został wysłany. Otwórz link na tym urządzeniu / w tej przeglądarce, aby kontynuować.' },
  AuthResetPasswordFailed: { en: 'Could not send reset email. Please try again.', pl: 'Nie udało się wysłać e-maila resetującego. Spróbuj ponownie.' },
  AdminPanelTitle: { en: 'Admin panel', pl: 'Panel admina' },
  AdminPanelSubtitle: { en: 'Protected operational view for feed freshness, coin coverage, and rollout readiness.', pl: 'Chroniony widok operacyjny dla świeżości feedu, pokrycia monet i gotowości wdrożenia.' },
  AdminSignInRequiredTitle: { en: 'Sign in required', pl: 'Wymagane logowanie' },
  AdminSignInRequiredBody: { en: 'The admin panel is protected. Sign in with an allowed admin email to review feed health and operational status.', pl: 'Panel admina jest chroniony. Zaloguj się dozwolonym adresem admina, aby sprawdzić stan feedu i operacji.' },
  AdminAccessDeniedTitle: { en: 'Access denied', pl: 'Brak dostępu' },
  AdminBackendUnavailableTitle: { en: 'Protected backend unavailable', pl: 'Chroniony backend niedostępny' },
  AdminAccessDeniedBody: { en: 'This signed-in account is not authorized for admin access.', pl: 'To zalogowane konto nie ma uprawnień do panelu admina.' },
  AdminBackendUnavailableBody: { en: 'The admin screen needs the protected backend function or a local fallback allowlist before it can reveal operational data.', pl: 'Ekran admina potrzebuje chronionej funkcji backendowej lub lokalnej listy awaryjnej, zanim pokaże dane operacyjne.' },
  AdminCheckingAccess: { en: 'Checking admin access…', pl: 'Sprawdzanie dostępu admina…' },
  AdminLoadingMetrics: { en: 'Loading admin metrics…', pl: 'Ładowanie metryk admina…' },
  AdminMetricsUnavailable: { en: 'Admin metrics unavailable', pl: 'Metryki admina niedostępne' },
  AdminAccessModeNote: { en: 'Access mode note', pl: 'Informacja o trybie dostępu' },
  AdminBackendAvailability: { en: 'Backend availability', pl: 'Dostępność backendu' },
  AdminBackendAvailabilityBody: { en: 'This panel prefers a JWT-protected admin function for internal tables. If that function is not deployed yet, it falls back to public market telemetry only.', pl: 'Ten panel preferuje chronioną funkcję admina z JWT dla tabel wewnętrznych. Jeśli funkcja nie jest jeszcze wdrożona, używa tylko publicznej telemetrii rynku.' },
  AdminEmailLabel: { en: 'Admin email', pl: 'E-mail admina' },
  AdminClientAllowlistConfigured: { en: 'Client allowlist configured', pl: 'Lista klienta skonfigurowana' },
  AdminClientFallbackAllowed: { en: 'Client fallback allowed', pl: 'Fallback klienta dozwolony' },
  AdminPrivilegedSource: { en: 'Privileged source', pl: 'Źródło uprzywilejowane' },
  AdminBackendAllowlistSource: { en: 'Backend allowlist source', pl: 'Źródło listy adminów backendu' },
  AdminFunctionDeployState: { en: 'Function deploy state', pl: 'Stan wdrożenia funkcji' },
  AdminAvailable: { en: 'available', pl: 'dostępne' },
  AdminUnavailableFallback: { en: 'unavailable / fallback', pl: 'niedostępne / fallback' },
  AdminUnknown: { en: 'unknown', pl: 'nieznane' },
  AdminIngestHealth: { en: 'Ingest health', pl: 'Stan ingestu' },
  AdminIngestHealthPrivilegedBody: { en: 'Privileged ingest metrics are live through the protected admin function.', pl: 'Uprzywilejowane metryki ingestu są dostępne przez chronioną funkcję admina.' },
  AdminIngestHealthFallbackBody: { en: 'Showing client-safe proxy based on the latest public snapshot batch until the protected admin function is deployed.', pl: 'Do czasu wdrożenia chronionej funkcji admina wyświetlany jest bezpieczny proxy oparty na ostatniej publicznej paczce snapshotów.' },
  AdminFeedStatus: { en: 'Feed status', pl: 'Status feedu' },
  AdminLatestSnapshot: { en: 'Latest snapshot', pl: 'Najnowszy snapshot' },
  Admin1hChangeGaps: { en: '1h change gaps', pl: 'Braki zmian 1h' },
  Admin24hChangeGaps: { en: '24h change gaps', pl: 'Braki zmian 24h' },
  AdminIngestRunsSampled: { en: 'Ingest runs sampled', pl: 'Zliczone przebiegi ingestu' },
  AdminFailedRuns24h: { en: 'Failed runs (24h)', pl: 'Błędne przebiegi (24h)' },
  AdminLastRun: { en: 'Last run', pl: 'Ostatni przebieg' },
  AdminLastFailure: { en: 'Last failure', pl: 'Ostatnia awaria' },
  AdminCoinDataStatus: { en: 'Coin data status', pl: 'Stan danych monet' },
  AdminMissingPrices: { en: 'Missing prices', pl: 'Brakujące ceny' },
  AdminSnapshotsStored: { en: 'Snapshots stored', pl: 'Zapisane snapshoty' },
  AdminWhaleMetricRows: { en: 'Whale metric rows', pl: 'Wiersze metryk wielorybów' },
  AdminTopTraderRows: { en: 'Top trader rows', pl: 'Wiersze top traderów' },
  AdminTopVolumeLeader: { en: 'Top volume leader', pl: 'Lider wolumenu' },
  AdminWatchlistSync: { en: 'Watchlist sync', pl: 'Synchronizacja watchlisty' },
  AdminModerationOps: { en: 'Moderation & ops', pl: 'Moderacja i operacje' },
  AdminWatchlistsCount: { en: 'Watchlists', pl: 'Watchlisty' },
  AdminWatchlistItemsCount: { en: 'Watchlist items', pl: 'Elementy watchlisty' },
  AdminActivityEventsCount: { en: 'Activity events', pl: 'Zdarzenia aktywności' },
  AdminModerationQueue: { en: 'Moderation queue', pl: 'Kolejka moderacji' },
  AdminNotAvailable: { en: 'not available', pl: 'niedostępne' },
  AdminBackToMenu: { en: 'Back to menu', pl: 'Wróć do menu' },
  PlaceholderAboutTitle: { en: 'About Yoink', pl: 'O Yoink' },
  PlaceholderAboutBody: { en: 'Yoink is a signal-first crypto discovery app focused on fast scanning, live lists, and high-conviction drill-downs.', pl: 'Yoink to aplikacja do odkrywania krypto stawiająca na sygnał, szybkie skanowanie, listy live i mocne wejścia w szczegóły.' },
  PlaceholderAboutBullet1: { en: 'AI Highlights for quick market-aware ideas', pl: 'Najważniejsze AI do szybkich pomysłów opartych na rynku' },
  PlaceholderAboutBullet2: { en: 'Explore for dense live market boards and rankings', pl: 'Odkrywaj dla gęstych tablic rynku live i rankingów' },
  PlaceholderAboutBullet3: { en: 'Protected admin tooling for ingest health and ops visibility', pl: 'Chronione narzędzia admina dla stanu ingestu i widoczności operacji' },
  PlaceholderLegalEyebrow: { en: 'Legal', pl: 'Prawne' },
  PlaceholderPrivacyTitle: { en: 'Privacy policy', pl: 'Polityka prywatności' },
  PlaceholderPrivacyBody: { en: 'A fuller privacy policy document will live here before broader public rollout.', pl: 'Pełniejszy dokument polityki prywatności pojawi się tutaj przed szerszym publicznym wdrożeniem.' },
  PlaceholderPrivacyBullet1: { en: 'What market data and account data Yoink stores', pl: 'Jakie dane rynkowe i konta przechowuje Yoink' },
  PlaceholderPrivacyBullet2: { en: 'What remains device-local vs synced to Supabase', pl: 'Co pozostaje lokalnie na urządzeniu, a co synchronizuje się z Supabase' },
  PlaceholderPrivacyBullet3: { en: 'How tester/admin access is controlled and audited', pl: 'Jak kontrolowany i audytowany jest dostęp testera/admina' },
  PlaceholderTermsTitle: { en: 'Terms of use', pl: 'Warunki korzystania' },
  PlaceholderTermsBody: { en: 'A fuller terms document will live here as the product moves beyond the current tester-focused phase.', pl: 'Pełniejszy dokument warunków pojawi się tutaj, gdy produkt wyjdzie poza obecną fazę testerów.' },
  PlaceholderTermsBullet1: { en: 'Usage rules for app data, signals, and alerts', pl: 'Zasady użycia danych aplikacji, sygnałów i alertów' },
  PlaceholderTermsBullet2: { en: 'Tester/admin responsibilities for internal environments', pl: 'Obowiązki testera/admina w środowiskach wewnętrznych' },
  PlaceholderTermsBullet3: { en: 'Future subscription and account terms', pl: 'Przyszłe warunki subskrypcji i konta' },
  PlaceholderSupportTitle: { en: 'Support hub', pl: 'Centrum wsparcia' },
  PlaceholderSupportBody: { en: 'Use the support section for help, privacy and security guidance, or to report a product issue.', pl: 'Używaj sekcji wsparcia do pomocy, wskazówek o prywatności i bezpieczeństwie lub zgłaszania problemów z produktem.' },
  PlaceholderSupportBullet1: { en: 'Help Center for FAQs and walkthrough content', pl: 'Centrum pomocy z FAQ i przewodnikami' },
  PlaceholderSupportBullet2: { en: 'Privacy & Security for account and data questions', pl: 'Prywatność i bezpieczeństwo dla pytań o konto i dane' },
  PlaceholderSupportBullet3: { en: 'Report Problem for bugs, broken flows, or incorrect market behavior', pl: 'Zgłoś problem dla błędów, zepsutych przepływów lub błędnego zachowania rynku' },
  PlaceholderHelpTitle: { en: 'Help content will live here', pl: 'Treści pomocy będą tutaj' },
  PlaceholderHelpBody: { en: 'This area will host quick-start guides, account help, and explanations of how lists, charts, and scouters work.', pl: 'To miejsce będzie zawierało szybkie przewodniki, pomoc do konta i wyjaśnienia działania list, wykresów i zwiadowców.' },
  PlaceholderHelpBullet1: { en: 'How AI Highlights and Explore lists are calculated', pl: 'Jak liczone są Najważniejsze AI i listy Odkrywaj' },
  PlaceholderHelpBullet2: { en: 'How to save, track, and revisit coins', pl: 'Jak zapisywać, śledzić i wracać do monet' },
  PlaceholderHelpBullet3: { en: 'How to use admin/tester flows safely during QA', pl: 'Jak bezpiecznie używać przepływów admin/tester podczas QA' },
  PlaceholderSecurityTitle: { en: 'Security guidance', pl: 'Wskazówki bezpieczeństwa' },
  PlaceholderSecurityBody: { en: 'This section will collect account-safety guidance, privacy details, and recovery instructions for Yoink users and testers.', pl: 'Ta sekcja będzie zbierać wskazówki bezpieczeństwa konta, szczegóły prywatności i instrukcje odzyskiwania dla użytkowników i testerów Yoink.' },
  PlaceholderSecurityBullet1: { en: 'Password, reset, and account recovery guidance', pl: 'Wskazówki dot. haseł, resetu i odzyskiwania konta' },
  PlaceholderSecurityBullet2: { en: 'What data is stored locally vs synced to your account', pl: 'Jakie dane są lokalne, a jakie synchronizowane z kontem' },
  PlaceholderSecurityBullet3: { en: 'How protected admin access is gated and audited', pl: 'Jak chroniony dostęp admina jest bramkowany i audytowany' },
  PlaceholderReportTitle: { en: 'Bug reporting flow', pl: 'Przepływ zgłaszania błędów' },
  PlaceholderReportBody: { en: 'This screen will become the structured path for reporting broken UI, incorrect market data, or auth/admin issues.', pl: 'Ten ekran stanie się uporządkowaną ścieżką do zgłaszania zepsutego UI, błędnych danych rynkowych lub problemów z auth/adminem.' },
  PlaceholderReportBullet1: { en: 'UI layout issues across Home, Explore, and detail pages', pl: 'Problemy z układem UI na Start, Odkrywaj i stronach szczegółów' },
  PlaceholderReportBullet2: { en: 'Incorrect prices, stale signals, or ingest-related errors', pl: 'Niepoprawne ceny, przestarzałe sygnały lub błędy związane z ingestem' },
  PlaceholderReportBullet3: { en: 'Tester/admin access problems and recovery details', pl: 'Problemy z dostępem testera/admina i szczegóły odzyskiwania' },
  PlaceholderSettingsTitle: { en: 'Choose a setting to edit', pl: 'Wybierz ustawienie do edycji' },
  PlaceholderSettingsBullet1: { en: 'Appearance controls for light, dark, and system theme', pl: 'Sterowanie wyglądem dla motywu jasnego, ciemnego i systemowego' },
  PlaceholderSettingsBullet2: { en: 'Language, currency, and notification preferences', pl: 'Preferencje języka, waluty i powiadomień' },
  PlaceholderSettingsBullet3: { en: 'Account-level options as they become available', pl: 'Opcje konta, gdy staną się dostępne' },
  PlaceholderNotificationsTitle: { en: 'Notification preferences', pl: 'Preferencje powiadomień' },
  PlaceholderNotificationsBullet1: { en: 'Price movement and momentum alerts', pl: 'Alerty o ruchach cen i momentum' },
  PlaceholderNotificationsBullet2: { en: 'Watchlist and scouter notifications', pl: 'Powiadomienia watchlist i zwiadowców' },
  PlaceholderNotificationsBullet3: { en: 'Important account and security messages', pl: 'Ważne wiadomości konta i bezpieczeństwa' },
  PlaceholderSubscriptionTitle: { en: 'Subscription plans', pl: 'Plany subskrypcji' },
  PlaceholderSubscriptionBullet1: { en: 'Future access to richer charting and advanced monitoring', pl: 'Przyszły dostęp do bogatszych wykresów i zaawansowanego monitoringu' },
  PlaceholderSubscriptionBullet2: { en: 'Expanded alerts, layouts, and premium signal surfaces', pl: 'Rozszerzone alerty, układy i premium sygnały' },
  PlaceholderSubscriptionBullet3: { en: 'Account-level billing and plan management', pl: 'Rozliczenia i zarządzanie planem na poziomie konta' },
  PlaceholderPortfolioTitle: { en: 'Portfolio tracking is coming next', pl: 'Śledzenie portfela nadchodzi' },
  PlaceholderPortfolioBody: { en: 'This screen will become your owned-position dashboard once portfolio ingestion and PnL tracking are wired into the product.', pl: 'Ten ekran stanie się Twoim panelem pozycji, gdy ingest portfela i śledzenie PnL zostaną podłączone do produktu.' },
  PlaceholderPortfolioBullet1: { en: 'Holdings summary, allocation, and daily portfolio movement', pl: 'Podsumowanie pozycji, alokacja i dzienny ruch portfela' },
  PlaceholderPortfolioBullet2: { en: 'Entry prices, unrealized profit/loss, and performance history', pl: 'Ceny wejścia, niezrealizowany zysk/strata i historia wyników' },
  PlaceholderPortfolioBullet3: { en: 'Quick jumps from positions into coin detail charts and scouters', pl: 'Szybkie przejścia z pozycji do szczegółowych wykresów monet i zwiadowców' },
  PlaceholderPortfolioNote: { en: 'For now, use Saved and Explore to track ideas while the portfolio layer is being built.', pl: 'Na razie używaj Zapisanych i Odkrywaj, aby śledzić pomysły, dopóki warstwa portfela nie zostanie zbudowana.' },
};

const dictionary: Record<string, Record<AppLanguage, string>> = Object.fromEntries(
  Object.entries(rawDictionary).map(([key, translations]) => {
    const filled: Record<AppLanguage, string> = {} as Record<AppLanguage, string>;
    SUPPORTED_LANGUAGES.forEach((lang) => {
      filled[lang] = translations[lang] ?? translations.en ?? Object.values(translations)[0] ?? key;
    });
    return [key, filled];
  }),
);

export function SettingsProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<AppLanguage>('en');
  const [currency, setCurrencyState] = useState<AppCurrency>('USD');

  useEffect(() => {
    (async () => {
      const [storedLang, storedCur] = await Promise.all([
        AsyncStorage.getItem(LANGUAGE_KEY),
        AsyncStorage.getItem(CURRENCY_KEY),
      ]);
      if (
        storedLang === 'en' || storedLang === 'de' || storedLang === 'fr' || storedLang === 'it' ||
        storedLang === 'es' || storedLang === 'pl' || storedLang === 'pt' || storedLang === 'tr' ||
        storedLang === 'ru' || storedLang === 'id' || storedLang === 'ms' || storedLang === 'th' ||
        storedLang === 'vi' || storedLang === 'ja' || storedLang === 'ko' || storedLang === 'zh' ||
        storedLang === 'zh-Hant' || storedLang === 'he' || storedLang === 'ar'
      ) {
        setLanguageState(storedLang);
      }
      if (storedCur === 'USD' || storedCur === 'EUR' || storedCur === 'KRW' || storedCur === 'JPY' || storedCur === 'CNY') {
        setCurrencyState(storedCur);
      }
    })();
  }, []);

  const setLanguage = (lang: AppLanguage) => {
    setLanguageState(lang);
    AsyncStorage.setItem(LANGUAGE_KEY, lang);
  };

  const setCurrency = (cur: AppCurrency) => {
    setCurrencyState(cur);
    AsyncStorage.setItem(CURRENCY_KEY, cur);
  };

  const locale = useMemo(() => localeMap[language], [language]);

  const t = (key: string) => {
    const entry = dictionary[key];
    if (!entry) return key;
    return entry[language] ?? entry['en'] ?? key;
    };

  const formatCurrency = (value: number, override?: { currency?: AppCurrency; language?: AppLanguage }) => {
    const cur = override?.currency ?? currency;
    const lang = override?.language ?? language;
    const loc = localeMap[lang];
    try {
      return new Intl.NumberFormat(loc, { style: 'currency', currency: cur, currencyDisplay: 'symbol' }).format(value);
    } catch {
      const symbol = currencySymbols[cur] ?? '';
      return `${symbol}${value.toFixed(2)}`;
    }
  };

  const ctx: SettingsContextType = {
    language,
    setLanguage,
    currency,
    setCurrency,
    locale,
    t,
    formatCurrency,
  };

  return <SettingsContext.Provider value={ctx}>{children}</SettingsContext.Provider>;
}

export function useSettings() {
  const ctx = useContext(SettingsContext);
  if (!ctx) throw new Error('useSettings must be used within SettingsProvider');
  return ctx;
}
